// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "_Base_global_variables.pypp.hpp"
#include "boost/python.hpp"
#include "sirebase_headers.h"

namespace bp = boost::python;

void register_global_variables(){

    bp::scope().attr("sharedpolypointer_magic") = SireBase::sharedpolypointer_magic;

}
