#!/usr/bin/env python

import sys
import os

if len(sys.argv) < 2:
    print >>sys.stderr,"USAGE: create_pbs_tmpdir  /path/to/tmpdir"
    sys.exit(-1)

tmpdir = sys.argv[1]

hostfile = os.getenv("PBS_NODEFILE")

hosts = []

if hostfile is None:
    hosts.append( "localhost" )

else:
    lines = open(hostfile, "r").readlines()

    all_nodes = {}

    for line in lines:
        words = line.lstrip().rstrip().split()

        if len(words) > 0:
            all_nodes[words[0]] = 1

    hosts = all_nodes.keys()

for host in hosts:
    os.system("ssh %s \"create_local_pbs_tmpdir %s\"" % (host, tmpdir))
