// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef CLJParameter_hpp__pyplusplus_wrapper
#define CLJParameter_hpp__pyplusplus_wrapper

void register_CLJParameter_class();

#endif//CLJParameter_hpp__pyplusplus_wrapper
