// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef InternalGenerator_MolAngleInfo__hpp__pyplusplus_wrapper
#define InternalGenerator_MolAngleInfo__hpp__pyplusplus_wrapper

void register_InternalGenerator_MolAngleInfo__class();

#endif//InternalGenerator_MolAngleInfo__hpp__pyplusplus_wrapper
