// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "ParameterSource.pypp.hpp"
#include "boost/python.hpp"
#include "sireff_headers.h"
#include "SireMol/molecule.h"
#include "SireMol/residue.h"
#include "SireMol/newatom.h"
#include "SireMol/atom.h"
#include "SireMol/cgatomid.h"
#include "SireMol/cutgroupnum.h"
#include "SireMol/resnumatomid.h"
#include "SireMol/resid.h"
#include "SireMol/moleculeid.h"

namespace bp = boost::python;

void register_ParameterSource_class(){

    bp::class_< SireFF::ParameterSource, bp::bases< SireFF::ParameterName > >( "ParameterSource" )    
        .def( bp::init< >() )    
        .def( 
            "isDefault"
            , (bool ( ::SireFF::ParameterSource::* )(  ) const)( &::SireFF::ParameterSource::isDefault ) )    
        .def( 
            "isValid"
            , (bool ( ::SireFF::ParameterSource::* )(  ) const)( &::SireFF::ParameterSource::isValid ) )    
        .def( bp::self != bp::self )    
        .def( bp::self == bp::self )    
        .def( 
            "source"
            , (::QString const & ( ::SireFF::ParameterSource::* )(  ) const)( &::SireFF::ParameterSource::source )
            , bp::return_value_policy< bp::copy_const_reference >() );

}
