// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef Molecule_protected_memfuns_hpp__pyplusplus_wrapper
#define Molecule_protected_memfuns_hpp__pyplusplus_wrapper

#include "_Molecule__wrapper.pypp.hpp"

void register_Molecule_protected_memfuns( Molecule_exposer_t& Molecule_exposer );

#endif//Molecule_protected_memfuns_hpp__pyplusplus_wrapper
