// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef NewAtom_enums_hpp__pyplusplus_wrapper
#define NewAtom_enums_hpp__pyplusplus_wrapper

#include "_NewAtom__wrapper.pypp.hpp"

void register_NewAtom_enums( NewAtom_exposer_t& NewAtom_exposer );

#endif//NewAtom_enums_hpp__pyplusplus_wrapper
