// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef ResidueBonds_hpp__pyplusplus_wrapper
#define ResidueBonds_hpp__pyplusplus_wrapper

void register_ResidueBonds_class();

#endif//ResidueBonds_hpp__pyplusplus_wrapper
