// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef NullGLMesh_hpp__pyplusplus_wrapper
#define NullGLMesh_hpp__pyplusplus_wrapper

void register_NullGLMesh_class();

#endif//NullGLMesh_hpp__pyplusplus_wrapper
