// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef NullCommand_hpp__pyplusplus_wrapper
#define NullCommand_hpp__pyplusplus_wrapper

void register_NullCommand_class();

#endif//NullCommand_hpp__pyplusplus_wrapper
