// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "ChainEditorBase.pypp.hpp"

namespace bp = boost::python;

#include "SireError/errors.h"

#include "SireStream/datastream.h"

#include "atom.h"

#include "atomeditor.h"

#include "chain.h"

#include "chaineditor.h"

#include "chainresid.h"

#include "groupatomids.h"

#include "molecule.h"

#include "moleditor.h"

#include "mover.hpp"

#include "reseditor.h"

#include "residue.h"

#include "segeditor.h"

#include "segment.h"

#include "selector.hpp"

#include "chaineditor.h"

#include "chainproperty.hpp"

SireMol::ChainEditorBase& set_Metadata_SireMol_ChainStringProperty_function1(
                                  SireMol::ChainEditorBase &molview,
                                   const QString &metakey, const QString &p)
                                   { return molview.setMetadata< QString >(metakey, p); }

SireMol::ChainEditorBase& set_Metadata_SireMol_ChainStringProperty_function2(
                                  SireMol::ChainEditorBase &molview,
                                   const QString &key, const QString &metakey, const QString &p)
                                   { return molview.setMetadata< QString >(key, metakey, p); }

SireMol::ChainEditorBase& set_Metadata_SireMol_ChainIntProperty_function1(
                                  SireMol::ChainEditorBase &molview,
                                   const QString &metakey, const qint64 &p)
                                   { return molview.setMetadata< qint64 >(metakey, p); }

SireMol::ChainEditorBase& set_Metadata_SireMol_ChainIntProperty_function2(
                                  SireMol::ChainEditorBase &molview,
                                   const QString &key, const QString &metakey, const qint64 &p)
                                   { return molview.setMetadata< qint64 >(key, metakey, p); }

SireMol::ChainEditorBase& set_Metadata_SireMol_ChainFloatProperty_function1(
                                  SireMol::ChainEditorBase &molview,
                                   const QString &metakey, const double &p)
                                   { return molview.setMetadata< double >(metakey, p); }

SireMol::ChainEditorBase& set_Metadata_SireMol_ChainFloatProperty_function2(
                                  SireMol::ChainEditorBase &molview,
                                   const QString &key, const QString &metakey, const double &p)
                                   { return molview.setMetadata< double >(key, metakey, p); }

SireMol::ChainEditorBase& set_Metadata_SireMol_ChainVariantProperty_function1(
                                  SireMol::ChainEditorBase &molview,
                                   const QString &metakey, const QVariant &p)
                                   { return molview.setMetadata< QVariant >(metakey, p); }

SireMol::ChainEditorBase& set_Metadata_SireMol_ChainVariantProperty_function2(
                                  SireMol::ChainEditorBase &molview,
                                   const QString &key, const QString &metakey, const QVariant &p)
                                   { return molview.setMetadata< QVariant >(key, metakey, p); }

#include "Helpers/str.hpp"

void register_ChainEditorBase_class(){

    { //::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >
        typedef bp::class_< SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >, bp::bases< SireMol::Chain, SireMol::MoleculeView, SireBase::Property >, boost::noncopyable > ChainEditorBase_exposer_t;
        ChainEditorBase_exposer_t ChainEditorBase_exposer = ChainEditorBase_exposer_t( "ChainEditorBase", bp::no_init );
        bp::scope ChainEditorBase_scope( ChainEditorBase_exposer );
        { //::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::operator=
        
            typedef SireMol::Editor< SireMol::ChainEditor, SireMol::Chain > exported_class_t;
            typedef ::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain > & ( ::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::*assign_function_type )( ::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain > const & ) ;
            assign_function_type assign_function_value( &::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::operator= );
            
            ChainEditorBase_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        { //::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::operator=
        
            typedef SireMol::Editor< SireMol::ChainEditor, SireMol::Chain > exported_class_t;
            typedef ::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain > & ( ::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::*assign_function_type )( ::SireMol::Chain const & ) ;
            assign_function_type assign_function_value( &::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::operator= );
            
            ChainEditorBase_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        { //::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::removeMetadata
        
            typedef SireMol::Editor< SireMol::ChainEditor, SireMol::Chain > exported_class_t;
            typedef ::SireMol::ChainEditor & ( ::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::*removeMetadata_function_type )( ::SireBase::PropertyName const & ) ;
            removeMetadata_function_type removeMetadata_function_value( &::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::removeMetadata );
            
            ChainEditorBase_exposer.def( 
                "removeMetadata"
                , removeMetadata_function_value
                , ( bp::arg("metakey") )
                , bp::return_self< >() );
        
        }
        { //::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::removeMetadata
        
            typedef SireMol::Editor< SireMol::ChainEditor, SireMol::Chain > exported_class_t;
            typedef ::SireMol::ChainEditor & ( ::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::*removeMetadata_function_type )( ::SireBase::PropertyName const &,::SireBase::PropertyName const & ) ;
            removeMetadata_function_type removeMetadata_function_value( &::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::removeMetadata );
            
            ChainEditorBase_exposer.def( 
                "removeMetadata"
                , removeMetadata_function_value
                , ( bp::arg("key"), bp::arg("metakey") )
                , bp::return_self< >() );
        
        }
        { //::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::removeProperty
        
            typedef SireMol::Editor< SireMol::ChainEditor, SireMol::Chain > exported_class_t;
            typedef ::SireMol::ChainEditor & ( ::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::*removeProperty_function_type )( ::SireBase::PropertyName const & ) ;
            removeProperty_function_type removeProperty_function_value( &::SireMol::Editor< SireMol::ChainEditor, SireMol::Chain >::removeProperty );
            
            ChainEditorBase_exposer.def( 
                "removeProperty"
                , removeProperty_function_value
                , ( bp::arg("key") )
                , bp::return_self< >() );
        
        }
        ChainEditorBase_exposer.def( "_set_property_QString", 
                                           &SireMol::ChainEditorBase::setProperty< QString >, bp::return_self< >() );
        ChainEditorBase_exposer.def( "_set_metadata_QString", &set_Metadata_SireMol_ChainStringProperty_function1, bp::return_self< >());
        ChainEditorBase_exposer.def( "_set_metadata_QString", &set_Metadata_SireMol_ChainStringProperty_function2, bp::return_self< >());
        ChainEditorBase_exposer.def( "_set_property_qint64", 
                                           &SireMol::ChainEditorBase::setProperty< qint64 >, bp::return_self< >() );
        ChainEditorBase_exposer.def( "_set_metadata_qint64", &set_Metadata_SireMol_ChainIntProperty_function1, bp::return_self< >());
        ChainEditorBase_exposer.def( "_set_metadata_qint64", &set_Metadata_SireMol_ChainIntProperty_function2, bp::return_self< >());
        ChainEditorBase_exposer.def( "_set_property_double", 
                                           &SireMol::ChainEditorBase::setProperty< double >, bp::return_self< >() );
        ChainEditorBase_exposer.def( "_set_metadata_double", &set_Metadata_SireMol_ChainFloatProperty_function1, bp::return_self< >());
        ChainEditorBase_exposer.def( "_set_metadata_double", &set_Metadata_SireMol_ChainFloatProperty_function2, bp::return_self< >());
        ChainEditorBase_exposer.def( "_set_property_QVariant", 
                                           &SireMol::ChainEditorBase::setProperty< QVariant >, bp::return_self< >() );
        ChainEditorBase_exposer.def( "_set_metadata_QVariant", &set_Metadata_SireMol_ChainVariantProperty_function1, bp::return_self< >());
        ChainEditorBase_exposer.def( "_set_metadata_QVariant", &set_Metadata_SireMol_ChainVariantProperty_function2, bp::return_self< >());
        ChainEditorBase_exposer.def( "__str__", &__str__< ::SireMol::Editor<SireMol::ChainEditor, SireMol::Chain> > );
        ChainEditorBase_exposer.def( "__repr__", &__str__< ::SireMol::Editor<SireMol::ChainEditor, SireMol::Chain> > );
    }

}
