// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef using_database_hpp__pyplusplus_wrapper
#define using_database_hpp__pyplusplus_wrapper

void register_using_database_class();

#endif//using_database_hpp__pyplusplus_wrapper
