// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef Mutable_hpp__pyplusplus_wrapper
#define Mutable_hpp__pyplusplus_wrapper

void register_Mutable_class();

#endif//Mutable_hpp__pyplusplus_wrapper
