// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef StringBase_hpp__pyplusplus_wrapper
#define StringBase_hpp__pyplusplus_wrapper

void register_StringBase_class();

#endif//StringBase_hpp__pyplusplus_wrapper
