// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef SpaceBase_hpp__pyplusplus_wrapper
#define SpaceBase_hpp__pyplusplus_wrapper

void register_SpaceBase_class();

#endif//SpaceBase_hpp__pyplusplus_wrapper
