// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "Cos.pypp.hpp"
#include "boost/python.hpp"
#include "sirecas_headers.h"

namespace bp = boost::python;

SireCAS::Cos __copy__(const SireCAS::Cos &other){ return SireCAS::Cos(other); }

#include "SireQt/qdatastream.hpp"

#include "SirePy/str.hpp"

void register_Cos_class(){

    bp::class_< SireCAS::Cos, bp::bases< SireCAS::SingleFunc > >( "Cos" )    
        .def( bp::init< >() )    
        .def( bp::init< SireCAS::Expression const & >(( bp::arg("ex") )) )    
        .def( 
            "evaluate"
            , (double ( ::SireCAS::Cos::* )( ::SireCAS::Values const & ) const)( &::SireCAS::Cos::evaluate )
            , ( bp::arg("values") ) )    
        .def( 
            "evaluate"
            , (::SireMaths::Complex ( ::SireCAS::Cos::* )( ::SireCAS::ComplexValues const & ) const)( &::SireCAS::Cos::evaluate )
            , ( bp::arg("values") ) )    
        .def( bp::self == bp::other< SireCAS::ExBase >() )    
        .def( 
            "typeName"
            , (char const * (*)(  ))( &::SireCAS::Cos::typeName ) )    
        .def( 
            "what"
            , (char const * ( ::SireCAS::Cos::* )(  ) const)( &::SireCAS::Cos::what ) )    
        .staticmethod( "typeName" )    
        .def( "__copy__", &__copy__)    
        .def( "__rlshift__", &SireQt::__rlshift__QDataStream< ::SireCAS::Cos >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() )    
        .def( "__rrshift__", &SireQt::__rrshift__QDataStream< ::SireCAS::Cos >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() )    
        .def( "__str__", &SirePy::__str__< ::SireCAS::Cos > );

}
