// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License


#include "boost/python.hpp"

#include "siremaths_headers.h"

#include "Angle.pypp.hpp"

#include "AxisSet.pypp.hpp"

#include "Complex.pypp.hpp"

#include "Line.pypp.hpp"

#include "Matrix.pypp.hpp"

#include "Matrix4.pypp.hpp"

#include "Plane.pypp.hpp"

#include "Quaternion.pypp.hpp"

#include "RanGenerator.pypp.hpp"

#include "Sphere.pypp.hpp"

#include "Torsion.pypp.hpp"

#include "Triangle.pypp.hpp"

#include "Vector.pypp.hpp"

#include "siremaths_containers.h"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_Maths){
    register_SireMaths_containers();

    register_Angle_class();

    register_Vector_class();

    register_AxisSet_class();

    register_Complex_class();

    register_Line_class();

    register_Matrix_class();

    register_Matrix4_class();

    register_Plane_class();

    register_Quaternion_class();

    register_RanGenerator_class();

    register_Sphere_class();

    register_Torsion_class();

    bp::implicitly_convertible< boost::tuples::tuple<double,double,double>, SireMaths::Vector >();

    bp::implicitly_convertible< double, SireMaths::Angle >();

    bp::implicitly_convertible< boost::tuples::tuple<SireMaths::Vector,SireMaths::Vector,SireMaths::Vector>, SireMaths::Matrix >();

    register_Triangle_class();
}

