#!/usr/bin/env python

import sys
import os
import shutil
from socket import gethostname

if len(sys.argv) < 2:
    print >>sys.stderr,"USAGE: remove_local_pbs_tmpdir /path/to/tmpdir"
    sys.exit(-1)

tmpdir = sys.argv[1]

if os.path.exists(tmpdir):
    print "Removing TMPDIR %s from %s..." % (tmpdir, gethostname())
    shutil.rmtree(tmpdir)
