// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef QVariant_hpp__pyplusplus_wrapper
#define QVariant_hpp__pyplusplus_wrapper

void register_QVariant_class();

#endif//QVariant_hpp__pyplusplus_wrapper
