// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "ArcCos.pypp.hpp"

namespace bp = boost::python;

#include "SireMaths/complex.h"

#include "SireMaths/errors.h"

#include "Siren/stream.h"

#include "complexvalues.h"

#include "exp.h"

#include "expression.h"

#include "identities.h"

#include "invtrigfuncs.h"

#include "trigfuncs.h"

#include "invtrigfuncs.h"

#include "Siren/logger.h"

SireCAS::ArcCos __copy__(const SireCAS::ArcCos &other){ return SireCAS::ArcCos(other); }

#include "Siren/str.hpp"

void register_ArcCos_class(){

    { //::SireCAS::ArcCos
        typedef bp::class_< SireCAS::ArcCos, bp::bases< SireCAS::SingleFunc, SireCAS::CASNode, Siren::Object > > ArcCos_exposer_t;
        ArcCos_exposer_t ArcCos_exposer = ArcCos_exposer_t( "ArcCos" );
        bp::scope ArcCos_scope( ArcCos_exposer );
        ArcCos_exposer.def( bp::init< >() );
        ArcCos_exposer.def( bp::init< SireCAS::Expression const & >(( bp::arg("ex") )) );
        ArcCos_exposer.def( bp::init< SireCAS::ArcCos const & >(( bp::arg("other") )) );
        { //::SireCAS::ArcCos::evaluate
        
            typedef double ( ::SireCAS::ArcCos::*evaluate_function_type )( ::SireCAS::Values const & ) const;
            evaluate_function_type evaluate_function_value( &::SireCAS::ArcCos::evaluate );
            
            ArcCos_exposer.def( 
                "evaluate"
                , evaluate_function_value
                , ( bp::arg("values") ) );
        
        }
        { //::SireCAS::ArcCos::evaluate
        
            typedef ::SireMaths::Complex ( ::SireCAS::ArcCos::*evaluate_function_type )( ::SireCAS::ComplexValues const & ) const;
            evaluate_function_type evaluate_function_value( &::SireCAS::ArcCos::evaluate );
            
            ArcCos_exposer.def( 
                "evaluate"
                , evaluate_function_value
                , ( bp::arg("values") ) );
        
        }
        ArcCos_exposer.def( bp::self != bp::self );
        { //::SireCAS::ArcCos::operator=
        
            typedef ::SireCAS::ArcCos & ( ::SireCAS::ArcCos::*assign_function_type )( ::SireCAS::ArcCos const & ) ;
            assign_function_type assign_function_value( &::SireCAS::ArcCos::operator= );
            
            ArcCos_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        ArcCos_exposer.def( bp::self == bp::self );
        { //::SireCAS::ArcCos::stream
        
            typedef void ( ::SireCAS::ArcCos::*stream_function_type )( ::Siren::Stream & ) ;
            stream_function_type stream_function_value( &::SireCAS::ArcCos::stream );
            
            ArcCos_exposer.def( 
                "stream"
                , stream_function_value
                , ( bp::arg("s") ) );
        
        }
        ArcCos_exposer.def( "__copy__", &__copy__);
        ArcCos_exposer.def( "__deepcopy__", &__copy__);
        ArcCos_exposer.def( "clone", &__copy__);
        ArcCos_exposer.def( "__str__", &__str__< ::SireCAS::ArcCos > );
        ArcCos_exposer.def( "__repr__", &__str__< ::SireCAS::ArcCos > );
    }

}
