// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "ArcSin.pypp.hpp"

namespace bp = boost::python;

#include "SireMaths/complex.h"

#include "SireMaths/errors.h"

#include "Siren/stream.h"

#include "complexvalues.h"

#include "exp.h"

#include "expression.h"

#include "identities.h"

#include "invtrigfuncs.h"

#include "trigfuncs.h"

#include "invtrigfuncs.h"

#include "Siren/logger.h"

SireCAS::ArcSin __copy__(const SireCAS::ArcSin &other){ return SireCAS::ArcSin(other); }

#include "Siren/str.hpp"

void register_ArcSin_class(){

    { //::SireCAS::ArcSin
        typedef bp::class_< SireCAS::ArcSin, bp::bases< SireCAS::SingleFunc, SireCAS::CASNode, Siren::Object > > ArcSin_exposer_t;
        ArcSin_exposer_t ArcSin_exposer = ArcSin_exposer_t( "ArcSin" );
        bp::scope ArcSin_scope( ArcSin_exposer );
        ArcSin_exposer.def( bp::init< >() );
        ArcSin_exposer.def( bp::init< SireCAS::Expression const & >(( bp::arg("ex") )) );
        ArcSin_exposer.def( bp::init< SireCAS::ArcSin const & >(( bp::arg("other") )) );
        { //::SireCAS::ArcSin::evaluate
        
            typedef double ( ::SireCAS::ArcSin::*evaluate_function_type )( ::SireCAS::Values const & ) const;
            evaluate_function_type evaluate_function_value( &::SireCAS::ArcSin::evaluate );
            
            ArcSin_exposer.def( 
                "evaluate"
                , evaluate_function_value
                , ( bp::arg("values") ) );
        
        }
        { //::SireCAS::ArcSin::evaluate
        
            typedef ::SireMaths::Complex ( ::SireCAS::ArcSin::*evaluate_function_type )( ::SireCAS::ComplexValues const & ) const;
            evaluate_function_type evaluate_function_value( &::SireCAS::ArcSin::evaluate );
            
            ArcSin_exposer.def( 
                "evaluate"
                , evaluate_function_value
                , ( bp::arg("values") ) );
        
        }
        ArcSin_exposer.def( bp::self != bp::self );
        { //::SireCAS::ArcSin::operator=
        
            typedef ::SireCAS::ArcSin & ( ::SireCAS::ArcSin::*assign_function_type )( ::SireCAS::ArcSin const & ) ;
            assign_function_type assign_function_value( &::SireCAS::ArcSin::operator= );
            
            ArcSin_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        ArcSin_exposer.def( bp::self == bp::self );
        { //::SireCAS::ArcSin::stream
        
            typedef void ( ::SireCAS::ArcSin::*stream_function_type )( ::Siren::Stream & ) ;
            stream_function_type stream_function_value( &::SireCAS::ArcSin::stream );
            
            ArcSin_exposer.def( 
                "stream"
                , stream_function_value
                , ( bp::arg("s") ) );
        
        }
        ArcSin_exposer.def( "__copy__", &__copy__);
        ArcSin_exposer.def( "__deepcopy__", &__copy__);
        ArcSin_exposer.def( "clone", &__copy__);
        ArcSin_exposer.def( "__str__", &__str__< ::SireCAS::ArcSin > );
        ArcSin_exposer.def( "__repr__", &__str__< ::SireCAS::ArcSin > );
    }

}
