// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "ArcTan.pypp.hpp"

namespace bp = boost::python;

#include "SireMaths/complex.h"

#include "SireMaths/errors.h"

#include "Siren/stream.h"

#include "complexvalues.h"

#include "exp.h"

#include "expression.h"

#include "identities.h"

#include "invtrigfuncs.h"

#include "trigfuncs.h"

#include "invtrigfuncs.h"

#include "Siren/logger.h"

SireCAS::ArcTan __copy__(const SireCAS::ArcTan &other){ return SireCAS::ArcTan(other); }

#include "Siren/str.hpp"

void register_ArcTan_class(){

    { //::SireCAS::ArcTan
        typedef bp::class_< SireCAS::ArcTan, bp::bases< SireCAS::SingleFunc, SireCAS::CASNode, Siren::Object > > ArcTan_exposer_t;
        ArcTan_exposer_t ArcTan_exposer = ArcTan_exposer_t( "ArcTan" );
        bp::scope ArcTan_scope( ArcTan_exposer );
        ArcTan_exposer.def( bp::init< >() );
        ArcTan_exposer.def( bp::init< SireCAS::Expression const & >(( bp::arg("ex") )) );
        ArcTan_exposer.def( bp::init< SireCAS::ArcTan const & >(( bp::arg("other") )) );
        { //::SireCAS::ArcTan::evaluate
        
            typedef double ( ::SireCAS::ArcTan::*evaluate_function_type )( ::SireCAS::Values const & ) const;
            evaluate_function_type evaluate_function_value( &::SireCAS::ArcTan::evaluate );
            
            ArcTan_exposer.def( 
                "evaluate"
                , evaluate_function_value
                , ( bp::arg("values") ) );
        
        }
        { //::SireCAS::ArcTan::evaluate
        
            typedef ::SireMaths::Complex ( ::SireCAS::ArcTan::*evaluate_function_type )( ::SireCAS::ComplexValues const & ) const;
            evaluate_function_type evaluate_function_value( &::SireCAS::ArcTan::evaluate );
            
            ArcTan_exposer.def( 
                "evaluate"
                , evaluate_function_value
                , ( bp::arg("values") ) );
        
        }
        ArcTan_exposer.def( bp::self != bp::self );
        { //::SireCAS::ArcTan::operator=
        
            typedef ::SireCAS::ArcTan & ( ::SireCAS::ArcTan::*assign_function_type )( ::SireCAS::ArcTan const & ) ;
            assign_function_type assign_function_value( &::SireCAS::ArcTan::operator= );
            
            ArcTan_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        ArcTan_exposer.def( bp::self == bp::self );
        { //::SireCAS::ArcTan::stream
        
            typedef void ( ::SireCAS::ArcTan::*stream_function_type )( ::Siren::Stream & ) ;
            stream_function_type stream_function_value( &::SireCAS::ArcTan::stream );
            
            ArcTan_exposer.def( 
                "stream"
                , stream_function_value
                , ( bp::arg("s") ) );
        
        }
        ArcTan_exposer.def( "__copy__", &__copy__);
        ArcTan_exposer.def( "__deepcopy__", &__copy__);
        ArcTan_exposer.def( "clone", &__copy__);
        ArcTan_exposer.def( "__str__", &__str__< ::SireCAS::ArcTan > );
        ArcTan_exposer.def( "__repr__", &__str__< ::SireCAS::ArcTan > );
    }

}
