// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "Csch.pypp.hpp"

namespace bp = boost::python;

#include "SireMaths/complex.h"

#include "Siren/stream.h"

#include "complexvalues.h"

#include "exp.h"

#include "expression.h"

#include "hyperbolicfuncs.h"

#include "identities.h"

#include "trigfuncs.h"

#include "hyperbolicfuncs.h"

#include "Siren/logger.h"

SireCAS::Csch __copy__(const SireCAS::Csch &other){ return SireCAS::Csch(other); }

#include "Siren/str.hpp"

void register_Csch_class(){

    { //::SireCAS::Csch
        typedef bp::class_< SireCAS::Csch, bp::bases< SireCAS::SingleFunc, SireCAS::CASNode, Siren::Object > > Csch_exposer_t;
        Csch_exposer_t Csch_exposer = Csch_exposer_t( "Csch" );
        bp::scope Csch_scope( Csch_exposer );
        Csch_exposer.def( bp::init< >() );
        Csch_exposer.def( bp::init< SireCAS::Expression const & >(( bp::arg("ex") )) );
        Csch_exposer.def( bp::init< SireCAS::Csch const & >(( bp::arg("other") )) );
        { //::SireCAS::Csch::evaluate
        
            typedef double ( ::SireCAS::Csch::*evaluate_function_type )( ::SireCAS::Values const & ) const;
            evaluate_function_type evaluate_function_value( &::SireCAS::Csch::evaluate );
            
            Csch_exposer.def( 
                "evaluate"
                , evaluate_function_value
                , ( bp::arg("values") ) );
        
        }
        { //::SireCAS::Csch::evaluate
        
            typedef ::SireMaths::Complex ( ::SireCAS::Csch::*evaluate_function_type )( ::SireCAS::ComplexValues const & ) const;
            evaluate_function_type evaluate_function_value( &::SireCAS::Csch::evaluate );
            
            Csch_exposer.def( 
                "evaluate"
                , evaluate_function_value
                , ( bp::arg("values") ) );
        
        }
        Csch_exposer.def( bp::self != bp::self );
        { //::SireCAS::Csch::operator=
        
            typedef ::SireCAS::Csch & ( ::SireCAS::Csch::*assign_function_type )( ::SireCAS::Csch const & ) ;
            assign_function_type assign_function_value( &::SireCAS::Csch::operator= );
            
            Csch_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        Csch_exposer.def( bp::self == bp::self );
        { //::SireCAS::Csch::stream
        
            typedef void ( ::SireCAS::Csch::*stream_function_type )( ::Siren::Stream & ) ;
            stream_function_type stream_function_value( &::SireCAS::Csch::stream );
            
            Csch_exposer.def( 
                "stream"
                , stream_function_value
                , ( bp::arg("s") ) );
        
        }
        Csch_exposer.def( "__copy__", &__copy__);
        Csch_exposer.def( "__deepcopy__", &__copy__);
        Csch_exposer.def( "clone", &__copy__);
        Csch_exposer.def( "__str__", &__str__< ::SireCAS::Csch > );
        Csch_exposer.def( "__repr__", &__str__< ::SireCAS::Csch > );
    }

}
