// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef MoverMove_hpp__pyplusplus_wrapper
#define MoverMove_hpp__pyplusplus_wrapper

void register_MoverMove_class();

#endif//MoverMove_hpp__pyplusplus_wrapper
