// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "AtomCutting.pypp.hpp"
#include "boost/python.hpp"
#include "siremol_headers.h"
#include "SireMaths/angle.h"
#include "SireMaths/quaternion.h"
#include "SireMaths/matrix.h"
#include "SireMaths/triangle.h"
#include "SireMaths/line.h"
#include "SireMaths/torsion.h"

namespace bp = boost::python;

void register_AtomCutting_class(){

    bp::class_< SireMol::AtomCutting, bp::bases< SireMol::CuttingFunctionBase > >( "AtomCutting" )    
        .def( bp::init< >() )    
        .def( 
            "__call__"
            , (::SireMol::CutGroupNum ( ::SireMol::AtomCutting::* )( ::SireMol::AtomIndex const &,::SireMol::EditMolData const & ) const)( &::SireMol::AtomCutting::operator() )
            , ( bp::arg("atom"), bp::arg("moldata") ) )    
        .def( 
            "typeName"
            , (char const * (*)(  ))( &::SireMol::AtomCutting::typeName ) )    
        .def( 
            "what"
            , (char const * ( ::SireMol::AtomCutting::* )(  ) const)( &::SireMol::AtomCutting::what ) )    
        .staticmethod( "typeName" );

}
