// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "CGAtomID.pypp.hpp"
#include "boost/python.hpp"
#include "siremol_headers.h"
#include "SireMol/moleculedata.h"
#include "SireMaths/angle.h"
#include "SireMaths/quaternion.h"
#include "SireMaths/matrix.h"
#include "SireMaths/triangle.h"
#include "SireMaths/line.h"
#include "SireMaths/torsion.h"

namespace bp = boost::python;

SireMol::CGAtomID __copy__(const SireMol::CGAtomID &other){ return SireMol::CGAtomID(other); }

#include "SireQt/qdatastream.hpp"

#include "SirePy/str.hpp"

void register_CGAtomID_class(){

    bp::class_< SireMol::CGAtomID >( "CGAtomID", bp::init< bp::optional< SireMol::CutGroupID, SireMol::AtomID > >(( bp::arg("cgid")=::SireMol::CutGroupID( 0 ), bp::arg("atmid")=::SireMol::AtomID( 0 ) )) )    
        .def( bp::init< boost::tuples::tuple<SireMol::CutGroupID, SireMol::AtomID, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> const & >(( bp::arg("t") )) )    
        .def( 
            "atomID"
            , &::SireMol::CGAtomID::atomID )    
        .def( 
            "cutGroupID"
            , &::SireMol::CGAtomID::cutGroupID )    
        .def( bp::self != bp::self )    
        .def( bp::self < bp::self )    
        .def( bp::self <= bp::self )    
        .def( bp::self == bp::self )    
        .def( bp::self > bp::self )    
        .def( bp::self >= bp::self )    
        .def( 
            "toString"
            , &::SireMol::CGAtomID::toString )    
        .def( "__copy__", &__copy__)    
        .def( "__rlshift__", &SireQt::__rlshift__QDataStream< ::SireMol::CGAtomID >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() )    
        .def( "__rrshift__", &SireQt::__rrshift__QDataStream< ::SireMol::CGAtomID >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() )    
        .def( "__str__", &SirePy::__str__< ::SireMol::CGAtomID > );

}
