// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "GroupIndexID.pypp.hpp"
#include "boost/python.hpp"
#include "siremol_headers.h"
#include "SireMol/moleculedata.h"
#include "SireMaths/quaternion.h"
#include "SireMaths/matrix.h"
#include "SireMaths/triangle.h"
#include "SireMaths/line.h"
#include "SireMaths/torsion.h"
#include "SireVol/space.h"

namespace bp = boost::python;

SireMol::GroupIndexID __copy__(const SireMol::GroupIndexID &other){ return SireMol::GroupIndexID(other); }

#include "SireQt/qdatastream.hpp"

#include "SirePy/str.hpp"

void register_GroupIndexID_class(){

    bp::class_< SireMol::GroupIndexID >( "GroupIndexID", bp::init< bp::optional< SireMol::GroupID, SireMol::Index > >(( bp::arg("gid")=::SireMol::GroupID( 0 ), bp::arg("idx")=::SireMol::Index( 0 ) )) )    
        .def( bp::init< boost::tuples::tuple<SireMol::GroupID, SireMol::Index, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> const & >(( bp::arg("t") )) )    
        .def( 
            "groupID"
            , &::SireMol::GroupIndexID::groupID )    
        .def( 
            "index"
            , &::SireMol::GroupIndexID::index )    
        .def( bp::self != bp::self )    
        .def( bp::self < bp::self )    
        .def( bp::self <= bp::self )    
        .def( bp::self == bp::self )    
        .def( bp::self > bp::self )    
        .def( bp::self >= bp::self )    
        .def( 
            "toString"
            , &::SireMol::GroupIndexID::toString )    
        .def( "__copy__", &__copy__)    
        .def( "__rlshift__", &SireQt::__rlshift__QDataStream< ::SireMol::GroupIndexID >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() )    
        .def( "__rrshift__", &SireQt::__rrshift__QDataStream< ::SireMol::GroupIndexID >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() )    
        .def( "__str__", &SirePy::__str__< ::SireMol::GroupIndexID > );

}
