// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef MoleculeVersion_hpp__pyplusplus_wrapper
#define MoleculeVersion_hpp__pyplusplus_wrapper

void register_MoleculeVersion_class();

#endif//MoleculeVersion_hpp__pyplusplus_wrapper
