// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "WeightFunction.pypp.hpp"
#include "boost/python.hpp"
#include "siremol_headers.h"
#include "SireMaths/angle.h"
#include "SireMaths/quaternion.h"
#include "SireMaths/matrix.h"
#include "SireMaths/triangle.h"
#include "SireMaths/line.h"
#include "SireMaths/torsion.h"

namespace bp = boost::python;

void register_WeightFunction_class(){

    bp::class_< SireMol::WeightFunction, boost::noncopyable >( "WeightFunction", bp::no_init )    
        .def( 
            "calculateWeight"
            , (double ( ::SireMol::WeightFunction::* )( ::SireMol::WeightCalculator const & ) const)( &::SireMol::WeightFunction::calculateWeight )
            , ( bp::arg("calculator") ) )    
        .def( 
            "processBuffers"
            , (void ( ::SireMol::WeightFunction::* )( ::SireMol::WeightCalculator & ) const)( &::SireMol::WeightFunction::processBuffers )
            , ( bp::arg("calculator") ) )    
        .def( 
            "what"
            , (char const * ( ::SireMol::WeightFunction::* )(  ) const)( &::SireMol::WeightFunction::what ) );

}
