// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "ArcCot.pypp.hpp"
#include "boost/python.hpp"
#include "sirecas_headers.h"

namespace bp = boost::python;

void register_ArcCot_class(){

    bp::class_< SireCAS::ArcCot, bp::bases< SireCAS::SingleFunc > >( "ArcCot" )    
        .def( bp::init< >() )    
        .def( bp::init< SireCAS::Expression const & >(( bp::arg("ex") )) )    
        .def( 
            "evaluate"
            , (double ( ::SireCAS::ArcCot::* )( ::SireCAS::Values const & ) const)( &::SireCAS::ArcCot::evaluate )
            , ( bp::arg("values") ) )    
        .def( 
            "evaluate"
            , (::SireMaths::Complex ( ::SireCAS::ArcCot::* )( ::SireCAS::ComplexValues const & ) const)( &::SireCAS::ArcCot::evaluate )
            , ( bp::arg("values") ) )    
        .def( bp::self == bp::other< SireCAS::ExBase >() )    
        .def( 
            "typeName"
            , (char const * (*)(  ))( &::SireCAS::ArcCot::typeName ) )    
        .def( 
            "what"
            , (char const * ( ::SireCAS::ArcCot::* )(  ) const)( &::SireCAS::ArcCot::what ) )    
        .staticmethod( "typeName" );

}
