// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "I.pypp.hpp"
#include "boost/python.hpp"
#include "sirecas_headers.h"

namespace bp = boost::python;

void register_I_class(){

    bp::class_< SireCAS::I, bp::bases< SireCAS::Constant > >( "I" )    
        .def( bp::init< >() )    
        .def( 
            "conjugate"
            , (::SireCAS::Expression ( ::SireCAS::I::* )(  ) const)( &::SireCAS::I::conjugate ) )    
        .def( 
            "evaluate"
            , (double ( ::SireCAS::I::* )( ::SireCAS::Values const & ) const)( &::SireCAS::I::evaluate )
            , ( bp::arg("arg0") ) )    
        .def( 
            "evaluate"
            , (::SireMaths::Complex ( ::SireCAS::I::* )( ::SireCAS::ComplexValues const & ) const)( &::SireCAS::I::evaluate )
            , ( bp::arg("arg0") ) )    
        .def( 
            "hash"
            , (::uint ( ::SireCAS::I::* )(  ) const)( &::SireCAS::I::hash ) )    
        .def( 
            "isComplex"
            , (bool ( ::SireCAS::I::* )(  ) const)( &::SireCAS::I::isComplex ) )    
        .def( bp::self == bp::other< SireCAS::ExBase >() )    
        .def( 
            "toString"
            , (::QString ( ::SireCAS::I::* )(  ) const)( &::SireCAS::I::toString ) )    
        .def( 
            "typeName"
            , (char const * (*)(  ))( &::SireCAS::I::typeName ) )    
        .def( 
            "what"
            , (char const * ( ::SireCAS::I::* )(  ) const)( &::SireCAS::I::what ) )    
        .staticmethod( "typeName" );

}
