// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "Power.pypp.hpp"
#include "boost/python.hpp"
#include "sirecas_headers.h"

namespace bp = boost::python;

void register_Power_class(){

    bp::class_< SireCAS::Power, bp::bases< SireCAS::PowerFunction > >( "Power" )    
        .def( bp::init< >() )    
        .def( bp::init< SireCAS::Expression const &, SireCAS::Expression const & >(( bp::arg("base"), bp::arg("power") )) )    
        .def( 
            "core"
            , (::SireCAS::Expression ( ::SireCAS::Power::* )(  ) const)( &::SireCAS::Power::core ) )    
        .def( 
            "evaluate"
            , (double ( ::SireCAS::Power::* )( ::SireCAS::Values const & ) const)( &::SireCAS::Power::evaluate )
            , ( bp::arg("values") ) )    
        .def( 
            "evaluate"
            , (::SireMaths::Complex ( ::SireCAS::Power::* )( ::SireCAS::ComplexValues const & ) const)( &::SireCAS::Power::evaluate )
            , ( bp::arg("values") ) )    
        .def( 
            "hash"
            , (::uint ( ::SireCAS::Power::* )(  ) const)( &::SireCAS::Power::hash ) )    
        .def( 
            "isCompound"
            , (bool ( ::SireCAS::Power::* )(  ) const)( &::SireCAS::Power::isCompound ) )    
        .def( bp::self == bp::other< SireCAS::ExBase >() )    
        .def( 
            "power"
            , (::SireCAS::Expression ( ::SireCAS::Power::* )(  ) const)( &::SireCAS::Power::power ) )    
        .def( 
            "typeName"
            , (char const * (*)(  ))( &::SireCAS::Power::typeName ) )    
        .def( 
            "what"
            , (char const * ( ::SireCAS::Power::* )(  ) const)( &::SireCAS::Power::what ) )    
        .staticmethod( "typeName" );

}
