// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "Helpers/clone_const_reference.hpp"
#include "AtomBeading.pypp.hpp"

namespace bp = boost::python;

#include "atombeading.h"

#include "atombeading.h"

#include "SireMaths/vector.h"

SireMol::AtomProperty<SireMol::BeadNum> __copy__(const SireMol::AtomProperty<SireMol::BeadNum> &other){ return SireMol::AtomProperty<SireMol::BeadNum>(other); }

#include "Qt/qdatastream.hpp"

#include "Helpers/str.hpp"

void register_AtomBeading_class(){

    { //::SireMol::AtomProperty< SireMol::BeadNum >
        typedef bp::class_< SireMol::AtomProperty< SireMol::BeadNum >, bp::bases< SireMol::AtomProp, SireMol::MolViewProperty, SireBase::Property > > AtomBeading_exposer_t;
        AtomBeading_exposer_t AtomBeading_exposer = AtomBeading_exposer_t( "AtomBeading" );
        bp::scope AtomBeading_scope( AtomBeading_exposer );
        AtomBeading_exposer.def( bp::init< >() );
        AtomBeading_exposer.def( bp::init< SireMol::MoleculeInfoData const & >(( bp::arg("molinfo") )) );
        AtomBeading_exposer.def( bp::init< SireMol::BeadNum const & >(( bp::arg("value") )) );
        AtomBeading_exposer.def( bp::init< SireBase::PackedArray2D< SireMol::BeadNum > const & >(( bp::arg("values") )) );
        AtomBeading_exposer.def( bp::init< SireMol::AtomProperty< SireMol::BeadNum > const & >(( bp::arg("other") )) );
        { //::SireMol::AtomProperty< SireMol::BeadNum >::array
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireBase::PackedArray2D< SireMol::BeadNum > const & ( ::SireMol::AtomProperty< SireMol::BeadNum >::*array_function_type )(  ) const;
            array_function_type array_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::array );
            
            AtomBeading_exposer.def( 
                "array"
                , array_function_value
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::assertCanConvert
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef void ( ::SireMol::AtomProperty< SireMol::BeadNum >::*assertCanConvert_function_type )( ::QVariant const & ) const;
            assertCanConvert_function_type assertCanConvert_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::assertCanConvert );
            
            AtomBeading_exposer.def( 
                "assertCanConvert"
                , assertCanConvert_function_value
                , ( bp::arg("value") ) );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::assignFrom
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef void ( ::SireMol::AtomProperty< SireMol::BeadNum >::*assignFrom_function_type )( ::SireMol::AtomProperty< QVariant > const & ) ;
            assignFrom_function_type assignFrom_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::assignFrom );
            
            AtomBeading_exposer.def( 
                "assignFrom"
                , assignFrom_function_value
                , ( bp::arg("values") ) );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::at
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireBase::detail::PackedArray2D_Array< SireMol::BeadNum > const & ( ::SireMol::AtomProperty< SireMol::BeadNum >::*at_function_type )( ::SireMol::CGIdx ) const;
            at_function_type at_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::at );
            
            AtomBeading_exposer.def( 
                "at"
                , at_function_value
                , ( bp::arg("cgidx") )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::at
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireMol::BeadNum const & ( ::SireMol::AtomProperty< SireMol::BeadNum >::*at_function_type )( ::SireMol::CGAtomIdx const & ) const;
            at_function_type at_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::at );
            
            AtomBeading_exposer.def( 
                "at"
                , at_function_value
                , ( bp::arg("cgatomidx") )
                , bp::return_value_policy<bp::clone_const_reference>() );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::canConvert
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef bool ( ::SireMol::AtomProperty< SireMol::BeadNum >::*canConvert_function_type )( ::QVariant const & ) const;
            canConvert_function_type canConvert_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::canConvert );
            
            AtomBeading_exposer.def( 
                "canConvert"
                , canConvert_function_value
                , ( bp::arg("value") ) );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::copyFrom
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef void ( ::SireMol::AtomProperty< SireMol::BeadNum >::*copyFrom_function_type )( ::QVector< SireMol::BeadNum > const & ) ;
            copyFrom_function_type copyFrom_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::copyFrom );
            
            AtomBeading_exposer.def( 
                "copyFrom"
                , copyFrom_function_value
                , ( bp::arg("values") ) );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::copyFrom
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef void ( ::SireMol::AtomProperty< SireMol::BeadNum >::*copyFrom_function_type )( ::QVector< SireMol::BeadNum > const &,::SireMol::AtomSelection const & ) ;
            copyFrom_function_type copyFrom_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::copyFrom );
            
            AtomBeading_exposer.def( 
                "copyFrom"
                , copyFrom_function_value
                , ( bp::arg("values"), bp::arg("selection") ) );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::count
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef int ( ::SireMol::AtomProperty< SireMol::BeadNum >::*count_function_type )(  ) const;
            count_function_type count_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::count );
            
            AtomBeading_exposer.def( 
                "count"
                , count_function_value );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::fromVariant
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireMol::AtomProperty< SireMol::BeadNum > ( *fromVariant_function_type )( ::SireMol::AtomProperty< QVariant > const & );
            fromVariant_function_type fromVariant_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::fromVariant );
            
            AtomBeading_exposer.def( 
                "fromVariant"
                , fromVariant_function_value
                , ( bp::arg("variant") ) );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::get
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireBase::detail::PackedArray2D_Array< SireMol::BeadNum > const & ( ::SireMol::AtomProperty< SireMol::BeadNum >::*get_function_type )( ::SireMol::CGIdx ) const;
            get_function_type get_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::get );
            
            AtomBeading_exposer.def( 
                "get"
                , get_function_value
                , ( bp::arg("cgidx") )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::get
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireMol::BeadNum const & ( ::SireMol::AtomProperty< SireMol::BeadNum >::*get_function_type )( ::SireMol::CGAtomIdx const & ) const;
            get_function_type get_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::get );
            
            AtomBeading_exposer.def( 
                "get"
                , get_function_value
                , ( bp::arg("cgatomidx") )
                , bp::return_value_policy<bp::clone_const_reference>() );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::isCompatibleWith
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef bool ( ::SireMol::AtomProperty< SireMol::BeadNum >::*isCompatibleWith_function_type )( ::SireMol::MoleculeInfoData const & ) const;
            isCompatibleWith_function_type isCompatibleWith_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::isCompatibleWith );
            
            AtomBeading_exposer.def( 
                "isCompatibleWith"
                , isCompatibleWith_function_value
                , ( bp::arg("molinfo") ) );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::isEmpty
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef bool ( ::SireMol::AtomProperty< SireMol::BeadNum >::*isEmpty_function_type )(  ) const;
            isEmpty_function_type isEmpty_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::isEmpty );
            
            AtomBeading_exposer.def( 
                "isEmpty"
                , isEmpty_function_value );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::matchToSelection
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireMol::AtomProperty< SireMol::BeadNum > ( ::SireMol::AtomProperty< SireMol::BeadNum >::*matchToSelection_function_type )( ::SireMol::AtomSelection const & ) const;
            matchToSelection_function_type matchToSelection_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::matchToSelection );
            
            AtomBeading_exposer.def( 
                "matchToSelection"
                , matchToSelection_function_value
                , ( bp::arg("selection") ) );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::nAtoms
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef int ( ::SireMol::AtomProperty< SireMol::BeadNum >::*nAtoms_function_type )(  ) const;
            nAtoms_function_type nAtoms_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::nAtoms );
            
            AtomBeading_exposer.def( 
                "nAtoms"
                , nAtoms_function_value );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::nAtoms
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef int ( ::SireMol::AtomProperty< SireMol::BeadNum >::*nAtoms_function_type )( ::SireMol::CGIdx ) const;
            nAtoms_function_type nAtoms_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::nAtoms );
            
            AtomBeading_exposer.def( 
                "nAtoms"
                , nAtoms_function_value
                , ( bp::arg("cgidx") ) );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::nCutGroups
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef int ( ::SireMol::AtomProperty< SireMol::BeadNum >::*nCutGroups_function_type )(  ) const;
            nCutGroups_function_type nCutGroups_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::nCutGroups );
            
            AtomBeading_exposer.def( 
                "nCutGroups"
                , nCutGroups_function_value );
        
        }
        AtomBeading_exposer.def( bp::self != bp::self );
        { //::SireMol::AtomProperty< SireMol::BeadNum >::operator=
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireMol::AtomProperty< SireMol::BeadNum > & ( ::SireMol::AtomProperty< SireMol::BeadNum >::*assign_function_type )( ::SireMol::AtomProperty< SireMol::BeadNum > const & ) ;
            assign_function_type assign_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::operator= );
            
            AtomBeading_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        AtomBeading_exposer.def( bp::self == bp::self );
        { //::SireMol::AtomProperty< SireMol::BeadNum >::operator[]
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireBase::detail::PackedArray2D_Array< SireMol::BeadNum > const & ( ::SireMol::AtomProperty< SireMol::BeadNum >::*__getitem___function_type )( ::SireMol::CGIdx ) const;
            __getitem___function_type __getitem___function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::operator[] );
            
            AtomBeading_exposer.def( 
                "__getitem__"
                , __getitem___function_value
                , ( bp::arg("cgidx") )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::operator[]
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireMol::BeadNum const & ( ::SireMol::AtomProperty< SireMol::BeadNum >::*__getitem___function_type )( ::SireMol::CGAtomIdx const & ) const;
            __getitem___function_type __getitem___function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::operator[] );
            
            AtomBeading_exposer.def( 
                "__getitem__"
                , __getitem___function_value
                , ( bp::arg("cgatomidx") )
                , bp::return_value_policy<bp::clone_const_reference>() );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::set
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireMol::AtomProperty< SireMol::BeadNum > & ( ::SireMol::AtomProperty< SireMol::BeadNum >::*set_function_type )( ::SireMol::CGAtomIdx const &,::SireMol::BeadNum const & ) ;
            set_function_type set_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::set );
            
            AtomBeading_exposer.def( 
                "set"
                , set_function_value
                , ( bp::arg("cgatomidx"), bp::arg("value") )
                , bp::return_self< >() );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::set
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireMol::AtomProperty< SireMol::BeadNum > & ( ::SireMol::AtomProperty< SireMol::BeadNum >::*set_function_type )( ::SireMol::CGIdx,::QVector< SireMol::BeadNum > const & ) ;
            set_function_type set_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::set );
            
            AtomBeading_exposer.def( 
                "set"
                , set_function_value
                , ( bp::arg("cgidx"), bp::arg("values") )
                , bp::return_self< >() );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::size
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef int ( ::SireMol::AtomProperty< SireMol::BeadNum >::*size_function_type )(  ) const;
            size_function_type size_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::size );
            
            AtomBeading_exposer.def( 
                "size"
                , size_function_value );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::toString
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::QString ( ::SireMol::AtomProperty< SireMol::BeadNum >::*toString_function_type )(  ) const;
            toString_function_type toString_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::toString );
            
            AtomBeading_exposer.def( 
                "toString"
                , toString_function_value );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::toVariant
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::SireMol::AtomProperty< QVariant > ( ::SireMol::AtomProperty< SireMol::BeadNum >::*toVariant_function_type )(  ) const;
            toVariant_function_type toVariant_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::toVariant );
            
            AtomBeading_exposer.def( 
                "toVariant"
                , toVariant_function_value );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::toVector
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::QVector< SireMol::BeadNum > ( ::SireMol::AtomProperty< SireMol::BeadNum >::*toVector_function_type )(  ) const;
            toVector_function_type toVector_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::toVector );
            
            AtomBeading_exposer.def( 
                "toVector"
                , toVector_function_value );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::toVector
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef ::QVector< SireMol::BeadNum > ( ::SireMol::AtomProperty< SireMol::BeadNum >::*toVector_function_type )( ::SireMol::AtomSelection const & ) const;
            toVector_function_type toVector_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::toVector );
            
            AtomBeading_exposer.def( 
                "toVector"
                , toVector_function_value
                , ( bp::arg("selection") ) );
        
        }
        { //::SireMol::AtomProperty< SireMol::BeadNum >::typeName
        
            typedef SireMol::AtomProperty< SireMol::BeadNum > exported_class_t;
            typedef char const * ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::SireMol::AtomProperty< SireMol::BeadNum >::typeName );
            
            AtomBeading_exposer.def( 
                "typeName"
                , typeName_function_value );
        
        }
        AtomBeading_exposer.staticmethod( "fromVariant" );
        AtomBeading_exposer.staticmethod( "typeName" );
        AtomBeading_exposer.def( "__copy__", &__copy__);
        AtomBeading_exposer.def( "__deepcopy__", &__copy__);
        AtomBeading_exposer.def( "clone", &__copy__);
        AtomBeading_exposer.def( "__rlshift__", &__rlshift__QDataStream< ::SireMol::AtomProperty<SireMol::BeadNum> >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        AtomBeading_exposer.def( "__rrshift__", &__rrshift__QDataStream< ::SireMol::AtomProperty<SireMol::BeadNum> >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        AtomBeading_exposer.def( "__str__", &__str__< ::SireMol::AtomProperty<SireMol::BeadNum> > );
        AtomBeading_exposer.def( "__repr__", &__str__< ::SireMol::AtomProperty<SireMol::BeadNum> > );
    }

}
