// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "SameMoves.pypp.hpp"
#include "boost/python.hpp"
#include "siresystem_headers.h"
#include "SireMol/molecule.h"
#include "SireMol/residue.h"
#include "SireMol/newatom.h"

namespace bp = boost::python;

void register_SameMoves_class(){

    bp::class_< SireSystem::SameMoves, bp::bases< SireSystem::MovesBase > >( "SameMoves" )    
        .def( bp::init< >() )    
        .def( bp::init< SireSystem::Move const & >(( bp::arg("move") )) )    
        .def( 
            "count"
            , &::SireSystem::SameMoves::count )    
        .def( 
            "initialise"
            , &::SireSystem::SameMoves::initialise
            , ( bp::arg("system") ) )    
        .def( 
            "typeName"
            , &::SireSystem::SameMoves::typeName )    
        .def( 
            "what"
            , &::SireSystem::SameMoves::what )    
        .staticmethod( "typeName" );

}
