// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef Option_hpp__pyplusplus_wrapper
#define Option_hpp__pyplusplus_wrapper

void register_Option_class();

#endif//Option_hpp__pyplusplus_wrapper
