// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "DihedralAtomID.pypp.hpp"
#include "boost/python.hpp"
#include "siremm_headers.h"
#include "SireMol/molecule.h"
#include "SireMol/residue.h"
#include "SireMol/newatom.h"
#include "SireMol/atom.h"

namespace bp = boost::python;

void register_DihedralAtomID_class(){

    bp::class_< SireMM::DihedralAtomID >( "DihedralAtomID" )    
        .def( bp::init< >() )    
        .def( bp::init< QString const &, QString const &, QString const &, QString const & >(( bp::arg("atom0"), bp::arg("atom1"), bp::arg("atom2"), bp::arg("atom3") )) )    
        .def( bp::init< SireMol::Dihedral const & >(( bp::arg("dihedral") )) )    
        .def( 
            "atom0"
            , (::QString const & ( ::SireMM::DihedralAtomID::* )(  ) const)( &::SireMM::DihedralAtomID::atom0 )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "atom1"
            , (::QString const & ( ::SireMM::DihedralAtomID::* )(  ) const)( &::SireMM::DihedralAtomID::atom1 )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "atom2"
            , (::QString const & ( ::SireMM::DihedralAtomID::* )(  ) const)( &::SireMM::DihedralAtomID::atom2 )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "atom3"
            , (::QString const & ( ::SireMM::DihedralAtomID::* )(  ) const)( &::SireMM::DihedralAtomID::atom3 )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( bp::self != bp::self )    
        .def( bp::self == bp::self )    
        .def( 
            "__getitem__"
            , (::QString const & ( ::SireMM::DihedralAtomID::* )( int ) const)( &::SireMM::DihedralAtomID::operator[] )
            , ( bp::arg("i") )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "size"
            , (int ( ::SireMM::DihedralAtomID::* )(  ) const)( &::SireMM::DihedralAtomID::size ) );

}
