// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "MolproCalculator.pypp.hpp"
#include "boost/python.hpp"
#include "squire_headers.h"
#include "SireMol/molecule.h"
#include "SireMol/residue.h"
#include "SireMol/newatom.h"

namespace bp = boost::python;

void register_MolproCalculator_class(){

    bp::class_< Squire::MolproCalculator, bp::bases< SireFF::FFCalculatorBase >, boost::noncopyable >( "MolproCalculator", bp::no_init )    
        .def( 
            "add"
            , (bool ( ::Squire::MolproCalculator::* )( ::SireMol::Molecule const &,::SireFF::ParameterMap const & ) )( &::Squire::MolproCalculator::add )
            , ( bp::arg("molecule"), bp::arg("map")=::SireFF::ParameterMap( ) ) )    
        .def( 
            "add"
            , (bool ( ::Squire::MolproCalculator::* )( ::SireMol::Residue const &,::SireFF::ParameterMap const & ) )( &::Squire::MolproCalculator::add )
            , ( bp::arg("residue"), bp::arg("map")=::SireFF::ParameterMap( ) ) )    
        .def( 
            "add"
            , (bool ( ::Squire::MolproCalculator::* )( ::SireMol::NewAtom const &,::SireFF::ParameterMap const & ) )( &::Squire::MolproCalculator::add )
            , ( bp::arg("atom"), bp::arg("map")=::SireFF::ParameterMap( ) ) )    
        .def( 
            "calculateEnergy"
            , (void ( ::Squire::MolproCalculator::* )(  ) )( &::Squire::MolproCalculator::calculateEnergy ) )    
        .def( 
            "change"
            , (bool ( ::Squire::MolproCalculator::* )( ::SireMol::Molecule const & ) )( &::Squire::MolproCalculator::change )
            , ( bp::arg("molecule") ) )    
        .def( 
            "change"
            , (bool ( ::Squire::MolproCalculator::* )( ::SireMol::Residue const & ) )( &::Squire::MolproCalculator::change )
            , ( bp::arg("residue") ) )    
        .def( 
            "change"
            , (bool ( ::Squire::MolproCalculator::* )( ::SireMol::NewAtom const & ) )( &::Squire::MolproCalculator::change )
            , ( bp::arg("atom") ) )    
        .def( 
            "forcefield"
            , (::SireFF::ForceField ( ::Squire::MolproCalculator::* )(  ) const)( &::Squire::MolproCalculator::forcefield ) )    
        .def( 
            "getEnergies"
            , (double ( ::Squire::MolproCalculator::* )( ::SireCAS::Values & ) )( &::Squire::MolproCalculator::getEnergies )
            , ( bp::arg("values") ) )    
        .def( 
            "remove"
            , (bool ( ::Squire::MolproCalculator::* )( ::SireMol::Molecule const & ) )( &::Squire::MolproCalculator::remove )
            , ( bp::arg("molecule") ) )    
        .def( 
            "remove"
            , (bool ( ::Squire::MolproCalculator::* )( ::SireMol::Residue const & ) )( &::Squire::MolproCalculator::remove )
            , ( bp::arg("residue") ) )    
        .def( 
            "remove"
            , (bool ( ::Squire::MolproCalculator::* )( ::SireMol::NewAtom const & ) )( &::Squire::MolproCalculator::remove )
            , ( bp::arg("atom") ) )    
        .def( 
            "replace"
            , (bool ( ::Squire::MolproCalculator::* )( ::SireMol::Molecule const &,::SireMol::Molecule const &,::SireFF::ParameterMap const & ) )( &::Squire::MolproCalculator::replace )
            , ( bp::arg("oldmol"), bp::arg("newmol"), bp::arg("map")=::SireFF::ParameterMap( ) ) )    
        .def( 
            "setForceField"
            , (bool ( ::Squire::MolproCalculator::* )( ::SireFF::ForceField const & ) )( &::Squire::MolproCalculator::setForceField )
            , ( bp::arg("forcefield") ) );

}
