// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef VolChangingFunctionBase_hpp__pyplusplus_wrapper
#define VolChangingFunctionBase_hpp__pyplusplus_wrapper

void register_VolChangingFunctionBase_class();

#endif//VolChangingFunctionBase_hpp__pyplusplus_wrapper
