// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License


#include "boost/python.hpp"

#include "_Sec_free_functions.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_Sec){
    register_free_functions();
}

