// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "Charge.pypp.hpp"
#include "boost/python.hpp"
#include "sireunits_headers.h"

namespace bp = boost::python;

SireUnits::Dimension::Charge __copy__(const SireUnits::Dimension::Charge &other){ return SireUnits::Dimension::Charge(other); }

const char* pvt_get_name(const SireUnits::Dimension::Charge&){ return "SireUnits::Dimension::Charge";}

void register_Charge_class(){

    bp::class_< SireUnits::Dimension::Charge, bp::bases< SireUnits::Dimension::Unit > >( "Charge", bp::init< double >(( bp::arg("scale_factor") )) )    
        .def( bp::other< double >() * bp::self )    
        .def( bp::other< double >() / bp::self )    
        .def( "__copy__", &__copy__)    
        .def( "__str__", &pvt_get_name);

}
