// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "Length.pypp.hpp"
#include "boost/python.hpp"
#include "sireunits_headers.h"

namespace bp = boost::python;

SireUnits::Dimension::Length __copy__(const SireUnits::Dimension::Length &other){ return SireUnits::Dimension::Length(other); }

const char* pvt_get_name(const SireUnits::Dimension::Length&){ return "SireUnits::Dimension::Length";}

void register_Length_class(){

    bp::class_< SireUnits::Dimension::Length, bp::bases< SireUnits::Dimension::Unit > >( "Length", bp::init< double >(( bp::arg("scale_factor") )) )    
        .def( bp::other< double >() * bp::self )    
        .def( bp::other< double >() / bp::self )    
        .def( "__copy__", &__copy__)    
        .def( "__str__", &pvt_get_name);

}
