// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef Quantity_hpp__pyplusplus_wrapper
#define Quantity_hpp__pyplusplus_wrapper

void register_Quantity_class();

#endif//Quantity_hpp__pyplusplus_wrapper
