// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "Unit.pypp.hpp"
#include "boost/python.hpp"
#include "sireunits_headers.h"

namespace bp = boost::python;

const char* pvt_get_name(const SireUnits::Dimension::Unit&){ return "SireUnits::Dimension::Unit";}

void register_Unit_class(){

    bp::class_< SireUnits::Dimension::Unit, boost::noncopyable >( "Unit", bp::no_init )    
        .def( 
            "convertFromInternal"
            , &::SireUnits::Dimension::Unit::convertFromInternal
            , ( bp::arg("value") ) )    
        .def( 
            "convertToInternal"
            , &::SireUnits::Dimension::Unit::convertToInternal
            , ( bp::arg("value") ) )    
        .def( "__float__", &SireUnits::Dimension::Unit::operator double  )    
        .def( 
            "scaleFactor"
            , &::SireUnits::Dimension::Unit::scaleFactor )    
        .def( "__str__", &pvt_get_name);

}
