#!/usr/bin/env python

import os
import sys

try:

    if len(sys.argv) > 1:
        jobid = sys.argv[1]
    else:
        jobid = os.getenv("PBS_JOBID")

    if jobid is None:
        print >>sys.stderr,"USAGE: get_remaining_queue_time (pbs_jobid)"
        sys.exit(-1)

    #we need to query the queue to get the amount of 
    #time left - this is only good to the nearest five
    #minutes!

    lines = os.popen("qstat -a %s" % jobid, "r").readlines()

    #the data is on the last line
    line = lines[-1]
            
    words = line.split()
            
    #get the requested and elapsed times
    (req_hours, req_mins) = words[-3].split(":")
            
    try:
        (elap_hours, elap_mins) = words[-1].split(":")
            
    except:
        (elap_hours, elap_mins) = (0,0)
            
    (req_hours, req_mins) = ( float(req_hours), float(req_mins) )
    (elap_hours, elap_mins) = ( float(elap_hours), float(elap_mins) )
            
    print (req_hours - elap_hours) * 3600 + \
          (req_mins - elap_mins) * 60

except:
    print >>sys.stderr,"Something went wrong!"
    print >>sys.stderr, sys.exc_info()[0]

    #We probably don't have any time left!
    print 0

    sys.exit(-1)

