// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef BondAtomID_hpp__pyplusplus_wrapper
#define BondAtomID_hpp__pyplusplus_wrapper

void register_BondAtomID_class();

#endif//BondAtomID_hpp__pyplusplus_wrapper
