// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "AABoxBase.pypp.hpp"

namespace bp = boost::python;

#include "SireMaths/sphere.h"

#include "Siren/datastream.h"

#include "Siren/errors.h"

#include "Siren/logger.h"

#include "Siren/tester.h"

#include "aabox.h"

#include "coordgroup.h"

#include <QDebug>

#include "aabox.h"

#include "Siren/logger.h"

Siren::Primitive<SireVol::AABox> __copy__(const Siren::Primitive<SireVol::AABox> &other){ return Siren::Primitive<SireVol::AABox>(other); }

const char* pvt_get_name(const Siren::Primitive<SireVol::AABox>&){ return "Siren::Primitive<SireVol::AABox>";}

void register_AABoxBase_class(){

    { //::Siren::Primitive< SireVol::AABox >
        typedef bp::class_< Siren::Primitive< SireVol::AABox > > AABoxBase_exposer_t;
        AABoxBase_exposer_t AABoxBase_exposer = AABoxBase_exposer_t( "AABoxBase" );
        bp::scope AABoxBase_scope( AABoxBase_exposer );
        AABoxBase_exposer.def( bp::init< >() );
        { //::Siren::Primitive< SireVol::AABox >::getClass
        
            typedef Siren::Primitive< SireVol::AABox > exported_class_t;
            typedef ::Siren::Class ( ::Siren::Primitive< SireVol::AABox >::*getClass_function_type )(  ) const;
            getClass_function_type getClass_function_value( &::Siren::Primitive< SireVol::AABox >::getClass );
            
            AABoxBase_exposer.def( 
                "getClass"
                , getClass_function_value );
        
        }
        { //::Siren::Primitive< SireVol::AABox >::hashCode
        
            typedef Siren::Primitive< SireVol::AABox > exported_class_t;
            typedef ::uint ( ::Siren::Primitive< SireVol::AABox >::*hashCode_function_type )(  ) const;
            hashCode_function_type hashCode_function_value( &::Siren::Primitive< SireVol::AABox >::hashCode );
            
            AABoxBase_exposer.def( 
                "hashCode"
                , hashCode_function_value );
        
        }
        { //::Siren::Primitive< SireVol::AABox >::load
        
            typedef Siren::Primitive< SireVol::AABox > exported_class_t;
            typedef void ( ::Siren::Primitive< SireVol::AABox >::*load_function_type )( ::Siren::Stream & ) ;
            load_function_type load_function_value( &::Siren::Primitive< SireVol::AABox >::load );
            
            AABoxBase_exposer.def( 
                "load"
                , load_function_value
                , ( bp::arg("s") ) );
        
        }
        AABoxBase_exposer.def( bp::self != bp::other< SireVol::AABox >() );
        { //::Siren::Primitive< SireVol::AABox >::save
        
            typedef Siren::Primitive< SireVol::AABox > exported_class_t;
            typedef void ( ::Siren::Primitive< SireVol::AABox >::*save_function_type )( ::Siren::Stream & ) const;
            save_function_type save_function_value( &::Siren::Primitive< SireVol::AABox >::save );
            
            AABoxBase_exposer.def( 
                "save"
                , save_function_value
                , ( bp::arg("s") ) );
        
        }
        { //::Siren::Primitive< SireVol::AABox >::stream
        
            typedef Siren::Primitive< SireVol::AABox > exported_class_t;
            typedef void ( ::Siren::Primitive< SireVol::AABox >::*stream_function_type )( ::Siren::Stream & ) ;
            stream_function_type stream_function_value( &::Siren::Primitive< SireVol::AABox >::stream );
            
            AABoxBase_exposer.def( 
                "stream"
                , stream_function_value
                , ( bp::arg("s") ) );
        
        }
        { //::Siren::Primitive< SireVol::AABox >::test
        
            typedef Siren::Primitive< SireVol::AABox > exported_class_t;
            typedef bool ( ::Siren::Primitive< SireVol::AABox >::*test_function_type )(  ) const;
            test_function_type test_function_value( &::Siren::Primitive< SireVol::AABox >::test );
            
            AABoxBase_exposer.def( 
                "test"
                , test_function_value );
        
        }
        { //::Siren::Primitive< SireVol::AABox >::test
        
            typedef Siren::Primitive< SireVol::AABox > exported_class_t;
            typedef bool ( ::Siren::Primitive< SireVol::AABox >::*test_function_type )( ::Siren::Logger & ) const;
            test_function_type test_function_value( &::Siren::Primitive< SireVol::AABox >::test );
            
            AABoxBase_exposer.def( 
                "test"
                , test_function_value
                , ( bp::arg("logger") ) );
        
        }
        { //::Siren::Primitive< SireVol::AABox >::typeName
        
            typedef Siren::Primitive< SireVol::AABox > exported_class_t;
            typedef ::QString ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::Siren::Primitive< SireVol::AABox >::typeName );
            
            AABoxBase_exposer.def( 
                "typeName"
                , typeName_function_value );
        
        }
        { //::Siren::Primitive< SireVol::AABox >::what
        
            typedef Siren::Primitive< SireVol::AABox > exported_class_t;
            typedef ::QString ( ::Siren::Primitive< SireVol::AABox >::*what_function_type )(  ) const;
            what_function_type what_function_value( &::Siren::Primitive< SireVol::AABox >::what );
            
            AABoxBase_exposer.def( 
                "what"
                , what_function_value );
        
        }
        AABoxBase_exposer.staticmethod( "typeName" );
        AABoxBase_exposer.def( "__copy__", &__copy__);
        AABoxBase_exposer.def( "__deepcopy__", &__copy__);
        AABoxBase_exposer.def( "clone", &__copy__);
        AABoxBase_exposer.def( "__str__", &pvt_get_name);
        AABoxBase_exposer.def( "__repr__", &pvt_get_name);
    }

}
