// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef EditMol_memfuns3_hpp__pyplusplus_wrapper
#define EditMol_memfuns3_hpp__pyplusplus_wrapper

#include "_EditMol__wrapper.pypp.hpp"

void register_EditMol_memfuns3( EditMol_exposer_t& EditMol_exposer );

#endif//EditMol_memfuns3_hpp__pyplusplus_wrapper
