// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "boost/python.hpp"
#include "siremol_headers.h"
#include "SireMaths/angle.h"
#include "SireMaths/quaternion.h"
#include "SireMaths/matrix.h"
#include "SireMaths/triangle.h"
#include "SireMaths/line.h"
#include "SireMaths/torsion.h"
#include "_EditRes__enums.pypp.hpp"
#include "_EditRes__unnamed_enums.pypp.hpp"
#include "_EditRes__classes.pypp.hpp"
#include "_EditRes__memfuns0.pypp.hpp"
#include "_EditRes__memfuns1.pypp.hpp"
#include "_EditRes__memfuns2.pypp.hpp"
#include "_EditRes__memfuns3.pypp.hpp"
#include "_EditRes__memfuns4.pypp.hpp"
#include "_EditRes__memfuns5.pypp.hpp"
#include "_EditRes__memfuns6.pypp.hpp"
#include "_EditRes__memfuns_virtual.pypp.hpp"
#include "_EditRes__memfuns_pvirtual.pypp.hpp"
#include "_EditRes__protected_memfuns.pypp.hpp"

namespace bp = boost::python;

SireMol::EditRes __copy__(const SireMol::EditRes &other){ return SireMol::EditRes(other); }

#include "SireQt/qdatastream.hpp"

const char* pvt_get_name(const SireMol::EditRes&){ return "SireMol::EditRes";}

void register_EditRes_class(){

{ //::SireMol::EditRes
    typedef bp::class_< SireMol::EditRes > EditRes_exposer_t;
    EditRes_exposer_t EditRes_exposer = EditRes_exposer_t( "EditRes" );
    bp::scope EditRes_scope( EditRes_exposer );
    EditRes_exposer.def( bp::init< >() );
    EditRes_exposer.def( bp::init< SireMol::EditMol const &, SireMol::ResNum >(( bp::arg("editmol"), bp::arg("resnum") )) );
    EditRes_exposer.def( bp::init< SireMol::EditMol const &, SireMol::ResID >(( bp::arg("editmol"), bp::arg("resid") )) );
    EditRes_exposer.def( bp::init< SireMol::EditMol const &, QString const & >(( bp::arg("editmol"), bp::arg("resname") )) );
    register_EditRes_memfuns0(EditRes_exposer);
    register_EditRes_memfuns1(EditRes_exposer);
    register_EditRes_memfuns2(EditRes_exposer);
    register_EditRes_memfuns3(EditRes_exposer);
    register_EditRes_memfuns4(EditRes_exposer);
    EditRes_exposer.def( bp::self != bp::self );
    EditRes_exposer.def( bp::self == bp::self );
    register_EditRes_memfuns5(EditRes_exposer);
    register_EditRes_memfuns6(EditRes_exposer);
    EditRes_exposer.def( "__copy__", &__copy__);
    EditRes_exposer.def( "__rlshift__", &SireQt::__rlshift__QDataStream< ::SireMol::EditRes >,
                        bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
    EditRes_exposer.def( "__rrshift__", &SireQt::__rrshift__QDataStream< ::SireMol::EditRes >,
                        bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
    EditRes_exposer.def( "__str__", &pvt_get_name);
}

}
