// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "EnergyMonitor.pypp.hpp"

namespace bp = boost::python;

#include "SireStream/datastream.h"

#include "SireStream/shareddatastream.h"

#include "SireSystem/energymonitor.h"

#include "SireSystem/system.h"

#include "energymonitor.h"

#include "energymonitor.h"

SireSystem::EnergyMonitor __copy__(const SireSystem::EnergyMonitor &other){ return SireSystem::EnergyMonitor(other); }

#include "Qt/qdatastream.hpp"

#include "Helpers/str.hpp"

void register_EnergyMonitor_class(){

    { //::SireSystem::EnergyMonitor
        typedef bp::class_< SireSystem::EnergyMonitor, bp::bases< SireSystem::SystemMonitor, SireBase::Property > > EnergyMonitor_exposer_t;
        EnergyMonitor_exposer_t EnergyMonitor_exposer = EnergyMonitor_exposer_t( "EnergyMonitor", bp::init< >() );
        bp::scope EnergyMonitor_scope( EnergyMonitor_exposer );
        EnergyMonitor_exposer.def( bp::init< SireMol::MoleculeGroup const &, SireMol::MoleculeGroup const & >(( bp::arg("group0"), bp::arg("group1") )) );
        EnergyMonitor_exposer.def( bp::init< SireMol::MoleculeGroup const &, SireMol::MoleculeGroup const &, SireMaths::Accumulator const & >(( bp::arg("group0"), bp::arg("group1"), bp::arg("accum") )) );
        EnergyMonitor_exposer.def( bp::init< SireSystem::EnergyMonitor const & >(( bp::arg("other") )) );
        { //::SireSystem::EnergyMonitor::clearStatistics
        
            typedef void ( ::SireSystem::EnergyMonitor::*clearStatistics_function_type )(  ) ;
            clearStatistics_function_type clearStatistics_function_value( &::SireSystem::EnergyMonitor::clearStatistics );
            
            EnergyMonitor_exposer.def( 
                "clearStatistics"
                , clearStatistics_function_value );
        
        }
        { //::SireSystem::EnergyMonitor::monitor
        
            typedef void ( ::SireSystem::EnergyMonitor::*monitor_function_type )( ::SireSystem::System & ) ;
            monitor_function_type monitor_function_value( &::SireSystem::EnergyMonitor::monitor );
            
            EnergyMonitor_exposer.def( 
                "monitor"
                , monitor_function_value
                , ( bp::arg("system") ) );
        
        }
        EnergyMonitor_exposer.def( bp::self != bp::self );
        { //::SireSystem::EnergyMonitor::operator=
        
            typedef ::SireSystem::EnergyMonitor & ( ::SireSystem::EnergyMonitor::*assign_function_type )( ::SireSystem::EnergyMonitor const & ) ;
            assign_function_type assign_function_value( &::SireSystem::EnergyMonitor::operator= );
            
            EnergyMonitor_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        EnergyMonitor_exposer.def( bp::self == bp::self );
        { //::SireSystem::EnergyMonitor::typeName
        
            typedef char const * ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::SireSystem::EnergyMonitor::typeName );
            
            EnergyMonitor_exposer.def( 
                "typeName"
                , typeName_function_value );
        
        }
        EnergyMonitor_exposer.staticmethod( "typeName" );
        EnergyMonitor_exposer.def( "__copy__", &__copy__);
        EnergyMonitor_exposer.def( "__deepcopy__", &__copy__);
        EnergyMonitor_exposer.def( "clone", &__copy__);
        EnergyMonitor_exposer.def( "__rlshift__", &__rlshift__QDataStream< ::SireSystem::EnergyMonitor >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        EnergyMonitor_exposer.def( "__rrshift__", &__rrshift__QDataStream< ::SireSystem::EnergyMonitor >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        EnergyMonitor_exposer.def( "__str__", &__str__< ::SireSystem::EnergyMonitor > );
        EnergyMonitor_exposer.def( "__repr__", &__str__< ::SireSystem::EnergyMonitor > );
    }

}
