// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "FreeEnergyAverage.pypp.hpp"

namespace bp = boost::python;

#include "SireUnits/units.h"

#include "freeenergyaverage.h"

#include "freeenergyaverage.h"

#include "Siren/logger.h"

SireMaths::FreeEnergyAverage __copy__(const SireMaths::FreeEnergyAverage &other){ return SireMaths::FreeEnergyAverage(other); }

#include "Siren/str.hpp"

void register_FreeEnergyAverage_class(){

    { //::SireMaths::FreeEnergyAverage
        typedef bp::class_< SireMaths::FreeEnergyAverage, bp::bases< SireMaths::ExpAverage, SireMaths::Accumulator, Siren::Mutable, Siren::Object > > FreeEnergyAverage_exposer_t;
        FreeEnergyAverage_exposer_t FreeEnergyAverage_exposer = FreeEnergyAverage_exposer_t( "FreeEnergyAverage" );
        bp::scope FreeEnergyAverage_scope( FreeEnergyAverage_exposer );
        FreeEnergyAverage_exposer.def( bp::init< >() );
        FreeEnergyAverage_exposer.def( bp::init< SireUnits::Dimension::Temperature const & >(( bp::arg("temperature") )) );
        FreeEnergyAverage_exposer.def( bp::init< SireMaths::FreeEnergyAverage const & >(( bp::arg("other") )) );
        { //::SireMaths::FreeEnergyAverage::hashCode
        
            typedef ::uint ( ::SireMaths::FreeEnergyAverage::*hashCode_function_type )(  ) const;
            hashCode_function_type hashCode_function_value( &::SireMaths::FreeEnergyAverage::hashCode );
            
            FreeEnergyAverage_exposer.def( 
                "hashCode"
                , hashCode_function_value );
        
        }
        FreeEnergyAverage_exposer.def( bp::self != bp::self );
        { //::SireMaths::FreeEnergyAverage::operator=
        
            typedef ::SireMaths::FreeEnergyAverage & ( ::SireMaths::FreeEnergyAverage::*assign_function_type )( ::SireMaths::FreeEnergyAverage const & ) ;
            assign_function_type assign_function_value( &::SireMaths::FreeEnergyAverage::operator= );
            
            FreeEnergyAverage_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        FreeEnergyAverage_exposer.def( bp::self == bp::self );
        { //::SireMaths::FreeEnergyAverage::stream
        
            typedef void ( ::SireMaths::FreeEnergyAverage::*stream_function_type )( ::Siren::Stream & ) ;
            stream_function_type stream_function_value( &::SireMaths::FreeEnergyAverage::stream );
            
            FreeEnergyAverage_exposer.def( 
                "stream"
                , stream_function_value
                , ( bp::arg("s") ) );
        
        }
        { //::SireMaths::FreeEnergyAverage::temperature
        
            typedef ::SireUnits::Dimension::Temperature ( ::SireMaths::FreeEnergyAverage::*temperature_function_type )(  ) const;
            temperature_function_type temperature_function_value( &::SireMaths::FreeEnergyAverage::temperature );
            
            FreeEnergyAverage_exposer.def( 
                "temperature"
                , temperature_function_value );
        
        }
        { //::SireMaths::FreeEnergyAverage::toString
        
            typedef ::QString ( ::SireMaths::FreeEnergyAverage::*toString_function_type )(  ) const;
            toString_function_type toString_function_value( &::SireMaths::FreeEnergyAverage::toString );
            
            FreeEnergyAverage_exposer.def( 
                "toString"
                , toString_function_value );
        
        }
        FreeEnergyAverage_exposer.def( "__copy__", &__copy__);
        FreeEnergyAverage_exposer.def( "__deepcopy__", &__copy__);
        FreeEnergyAverage_exposer.def( "clone", &__copy__);
        FreeEnergyAverage_exposer.def( "__str__", &__str__< ::SireMaths::FreeEnergyAverage > );
        FreeEnergyAverage_exposer.def( "__repr__", &__str__< ::SireMaths::FreeEnergyAverage > );
    }

}
