// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "HistogramBin.pypp.hpp"

namespace bp = boost::python;

#include "SireID/index.h"

#include "Siren/errors.h"

#include "Siren/stream.h"

#include "Siren/streamqt.h"

#include "histogram.h"

#include "histogram.h"

#include "Siren/logger.h"

SireMaths::HistogramBin __copy__(const SireMaths::HistogramBin &other){ return SireMaths::HistogramBin(other); }

#include "Siren/str.hpp"

void register_HistogramBin_class(){

    { //::SireMaths::HistogramBin
        typedef bp::class_< SireMaths::HistogramBin, bp::bases< Siren::Object > > HistogramBin_exposer_t;
        HistogramBin_exposer_t HistogramBin_exposer = HistogramBin_exposer_t( "HistogramBin" );
        bp::scope HistogramBin_scope( HistogramBin_exposer );
        HistogramBin_exposer.def( bp::init< >() );
        HistogramBin_exposer.def( bp::init< double, double >(( bp::arg("minval"), bp::arg("maxval") )) );
        HistogramBin_exposer.def( bp::init< SireMaths::HistogramBin const & >(( bp::arg("other") )) );
        { //::SireMaths::HistogramBin::hashCode
        
            typedef ::uint ( ::SireMaths::HistogramBin::*hashCode_function_type )(  ) const;
            hashCode_function_type hashCode_function_value( &::SireMaths::HistogramBin::hashCode );
            
            HistogramBin_exposer.def( 
                "hashCode"
                , hashCode_function_value );
        
        }
        { //::SireMaths::HistogramBin::maximum
        
            typedef double ( ::SireMaths::HistogramBin::*maximum_function_type )(  ) const;
            maximum_function_type maximum_function_value( &::SireMaths::HistogramBin::maximum );
            
            HistogramBin_exposer.def( 
                "maximum"
                , maximum_function_value );
        
        }
        { //::SireMaths::HistogramBin::middle
        
            typedef double ( ::SireMaths::HistogramBin::*middle_function_type )(  ) const;
            middle_function_type middle_function_value( &::SireMaths::HistogramBin::middle );
            
            HistogramBin_exposer.def( 
                "middle"
                , middle_function_value );
        
        }
        { //::SireMaths::HistogramBin::minimum
        
            typedef double ( ::SireMaths::HistogramBin::*minimum_function_type )(  ) const;
            minimum_function_type minimum_function_value( &::SireMaths::HistogramBin::minimum );
            
            HistogramBin_exposer.def( 
                "minimum"
                , minimum_function_value );
        
        }
        HistogramBin_exposer.def( bp::self != bp::self );
        { //::SireMaths::HistogramBin::operator=
        
            typedef ::SireMaths::HistogramBin & ( ::SireMaths::HistogramBin::*assign_function_type )( ::SireMaths::HistogramBin const & ) ;
            assign_function_type assign_function_value( &::SireMaths::HistogramBin::operator= );
            
            HistogramBin_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        HistogramBin_exposer.def( bp::self == bp::self );
        { //::SireMaths::HistogramBin::stream
        
            typedef void ( ::SireMaths::HistogramBin::*stream_function_type )( ::Siren::Stream & ) ;
            stream_function_type stream_function_value( &::SireMaths::HistogramBin::stream );
            
            HistogramBin_exposer.def( 
                "stream"
                , stream_function_value
                , ( bp::arg("s") ) );
        
        }
        { //::SireMaths::HistogramBin::toString
        
            typedef ::QString ( ::SireMaths::HistogramBin::*toString_function_type )(  ) const;
            toString_function_type toString_function_value( &::SireMaths::HistogramBin::toString );
            
            HistogramBin_exposer.def( 
                "toString"
                , toString_function_value );
        
        }
        HistogramBin_exposer.def( "__copy__", &__copy__);
        HistogramBin_exposer.def( "__deepcopy__", &__copy__);
        HistogramBin_exposer.def( "clone", &__copy__);
        HistogramBin_exposer.def( "__str__", &__str__< ::SireMaths::HistogramBin > );
        HistogramBin_exposer.def( "__repr__", &__str__< ::SireMaths::HistogramBin > );
    }

}
