// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "MatrixBase.pypp.hpp"

namespace bp = boost::python;

#include "SireMaths/errors.h"

#include "Siren/errors.h"

#include "Siren/stream.h"

#include "maths.h"

#include "matrix.h"

#include "vector.h"

#include <QString>

#include <boost/scoped_array.hpp>

#include <gsl/gsl_eigen.h>

#include <gsl/gsl_matrix.h>

#include <gsl/gsl_vector.h>

#include "matrix.h"

#include "Siren/logger.h"

Siren::Primitive<SireMaths::Matrix> __copy__(const Siren::Primitive<SireMaths::Matrix> &other){ return Siren::Primitive<SireMaths::Matrix>(other); }

const char* pvt_get_name(const Siren::Primitive<SireMaths::Matrix>&){ return "Siren::Primitive<SireMaths::Matrix>";}

void register_MatrixBase_class(){

    { //::Siren::Primitive< SireMaths::Matrix >
        typedef bp::class_< Siren::Primitive< SireMaths::Matrix > > MatrixBase_exposer_t;
        MatrixBase_exposer_t MatrixBase_exposer = MatrixBase_exposer_t( "MatrixBase" );
        bp::scope MatrixBase_scope( MatrixBase_exposer );
        MatrixBase_exposer.def( bp::init< >() );
        { //::Siren::Primitive< SireMaths::Matrix >::getClass
        
            typedef Siren::Primitive< SireMaths::Matrix > exported_class_t;
            typedef ::Siren::Class ( ::Siren::Primitive< SireMaths::Matrix >::*getClass_function_type )(  ) const;
            getClass_function_type getClass_function_value( &::Siren::Primitive< SireMaths::Matrix >::getClass );
            
            MatrixBase_exposer.def( 
                "getClass"
                , getClass_function_value );
        
        }
        { //::Siren::Primitive< SireMaths::Matrix >::hashCode
        
            typedef Siren::Primitive< SireMaths::Matrix > exported_class_t;
            typedef ::uint ( ::Siren::Primitive< SireMaths::Matrix >::*hashCode_function_type )(  ) const;
            hashCode_function_type hashCode_function_value( &::Siren::Primitive< SireMaths::Matrix >::hashCode );
            
            MatrixBase_exposer.def( 
                "hashCode"
                , hashCode_function_value );
        
        }
        { //::Siren::Primitive< SireMaths::Matrix >::load
        
            typedef Siren::Primitive< SireMaths::Matrix > exported_class_t;
            typedef void ( ::Siren::Primitive< SireMaths::Matrix >::*load_function_type )( ::Siren::Stream & ) ;
            load_function_type load_function_value( &::Siren::Primitive< SireMaths::Matrix >::load );
            
            MatrixBase_exposer.def( 
                "load"
                , load_function_value
                , ( bp::arg("s") ) );
        
        }
        MatrixBase_exposer.def( bp::self != bp::other< SireMaths::Matrix >() );
        { //::Siren::Primitive< SireMaths::Matrix >::save
        
            typedef Siren::Primitive< SireMaths::Matrix > exported_class_t;
            typedef void ( ::Siren::Primitive< SireMaths::Matrix >::*save_function_type )( ::Siren::Stream & ) const;
            save_function_type save_function_value( &::Siren::Primitive< SireMaths::Matrix >::save );
            
            MatrixBase_exposer.def( 
                "save"
                , save_function_value
                , ( bp::arg("s") ) );
        
        }
        { //::Siren::Primitive< SireMaths::Matrix >::stream
        
            typedef Siren::Primitive< SireMaths::Matrix > exported_class_t;
            typedef void ( ::Siren::Primitive< SireMaths::Matrix >::*stream_function_type )( ::Siren::Stream & ) ;
            stream_function_type stream_function_value( &::Siren::Primitive< SireMaths::Matrix >::stream );
            
            MatrixBase_exposer.def( 
                "stream"
                , stream_function_value
                , ( bp::arg("s") ) );
        
        }
        { //::Siren::Primitive< SireMaths::Matrix >::test
        
            typedef Siren::Primitive< SireMaths::Matrix > exported_class_t;
            typedef bool ( ::Siren::Primitive< SireMaths::Matrix >::*test_function_type )(  ) const;
            test_function_type test_function_value( &::Siren::Primitive< SireMaths::Matrix >::test );
            
            MatrixBase_exposer.def( 
                "test"
                , test_function_value );
        
        }
        { //::Siren::Primitive< SireMaths::Matrix >::test
        
            typedef Siren::Primitive< SireMaths::Matrix > exported_class_t;
            typedef bool ( ::Siren::Primitive< SireMaths::Matrix >::*test_function_type )( ::Siren::Logger & ) const;
            test_function_type test_function_value( &::Siren::Primitive< SireMaths::Matrix >::test );
            
            MatrixBase_exposer.def( 
                "test"
                , test_function_value
                , ( bp::arg("logger") ) );
        
        }
        { //::Siren::Primitive< SireMaths::Matrix >::typeName
        
            typedef Siren::Primitive< SireMaths::Matrix > exported_class_t;
            typedef ::QString ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::Siren::Primitive< SireMaths::Matrix >::typeName );
            
            MatrixBase_exposer.def( 
                "typeName"
                , typeName_function_value );
        
        }
        { //::Siren::Primitive< SireMaths::Matrix >::what
        
            typedef Siren::Primitive< SireMaths::Matrix > exported_class_t;
            typedef ::QString ( ::Siren::Primitive< SireMaths::Matrix >::*what_function_type )(  ) const;
            what_function_type what_function_value( &::Siren::Primitive< SireMaths::Matrix >::what );
            
            MatrixBase_exposer.def( 
                "what"
                , what_function_value );
        
        }
        MatrixBase_exposer.staticmethod( "typeName" );
        MatrixBase_exposer.def( "__copy__", &__copy__);
        MatrixBase_exposer.def( "__deepcopy__", &__copy__);
        MatrixBase_exposer.def( "clone", &__copy__);
        MatrixBase_exposer.def( "__str__", &pvt_get_name);
        MatrixBase_exposer.def( "__repr__", &pvt_get_name);
    }

}
