// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "Torsion.pypp.hpp"

namespace bp = boost::python;

#include "SireUnits/units.h"

#include "Siren/stream.h"

#include "torsion.h"

#include "torsion.h"

#include "Siren/logger.h"

SireMaths::Torsion __copy__(const SireMaths::Torsion &other){ return SireMaths::Torsion(other); }

#include "Siren/str.hpp"

void register_Torsion_class(){

    { //::SireMaths::Torsion
        typedef bp::class_< SireMaths::Torsion, bp::bases< Siren::Primitive<SireMaths::Torsion> > > Torsion_exposer_t;
        Torsion_exposer_t Torsion_exposer = Torsion_exposer_t( "Torsion" );
        bp::scope Torsion_scope( Torsion_exposer );
        Torsion_exposer.def( bp::init< >() );
        Torsion_exposer.def( bp::init< SireMaths::Vector const &, SireMaths::Vector const &, SireMaths::Vector const &, SireMaths::Vector const & >(( bp::arg("point0"), bp::arg("point1"), bp::arg("point2"), bp::arg("point3") )) );
        { //::SireMaths::Torsion::angle
        
            typedef ::SireUnits::Dimension::Angle ( ::SireMaths::Torsion::*angle_function_type )(  ) const;
            angle_function_type angle_function_value( &::SireMaths::Torsion::angle );
            
            Torsion_exposer.def( 
                "angle"
                , angle_function_value );
        
        }
        { //::SireMaths::Torsion::at
        
            typedef ::SireMaths::Vector const & ( ::SireMaths::Torsion::*at_function_type )( int ) const;
            at_function_type at_function_value( &::SireMaths::Torsion::at );
            
            Torsion_exposer.def( 
                "at"
                , at_function_value
                , ( bp::arg("i") )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::SireMaths::Torsion::count
        
            typedef int ( ::SireMaths::Torsion::*count_function_type )(  ) const;
            count_function_type count_function_value( &::SireMaths::Torsion::count );
            
            Torsion_exposer.def( 
                "count"
                , count_function_value );
        
        }
        { //::SireMaths::Torsion::hashCode
        
            typedef ::uint ( ::SireMaths::Torsion::*hashCode_function_type )(  ) const;
            hashCode_function_type hashCode_function_value( &::SireMaths::Torsion::hashCode );
            
            Torsion_exposer.def( 
                "hashCode"
                , hashCode_function_value );
        
        }
        { //::SireMaths::Torsion::improperAngle
        
            typedef ::SireUnits::Dimension::Angle ( ::SireMaths::Torsion::*improperAngle_function_type )(  ) const;
            improperAngle_function_type improperAngle_function_value( &::SireMaths::Torsion::improperAngle );
            
            Torsion_exposer.def( 
                "improperAngle"
                , improperAngle_function_value );
        
        }
        { //::SireMaths::Torsion::line03
        
            typedef ::SireMaths::Line ( ::SireMaths::Torsion::*line03_function_type )(  ) const;
            line03_function_type line03_function_value( &::SireMaths::Torsion::line03 );
            
            Torsion_exposer.def( 
                "line03"
                , line03_function_value );
        
        }
        { //::SireMaths::Torsion::line12
        
            typedef ::SireMaths::Line ( ::SireMaths::Torsion::*line12_function_type )(  ) const;
            line12_function_type line12_function_value( &::SireMaths::Torsion::line12 );
            
            Torsion_exposer.def( 
                "line12"
                , line12_function_value );
        
        }
        Torsion_exposer.def( bp::self != bp::self );
        { //::SireMaths::Torsion::operator=
        
            typedef ::SireMaths::Torsion & ( ::SireMaths::Torsion::*assign_function_type )( ::SireMaths::Torsion const & ) ;
            assign_function_type assign_function_value( &::SireMaths::Torsion::operator= );
            
            Torsion_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        Torsion_exposer.def( bp::self == bp::self );
        { //::SireMaths::Torsion::operator[]
        
            typedef ::SireMaths::Vector const & ( ::SireMaths::Torsion::*__getitem___function_type )( int ) const;
            __getitem___function_type __getitem___function_value( &::SireMaths::Torsion::operator[] );
            
            Torsion_exposer.def( 
                "__getitem__"
                , __getitem___function_value
                , ( bp::arg("i") )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::SireMaths::Torsion::point
        
            typedef ::SireMaths::Vector const & ( ::SireMaths::Torsion::*point_function_type )( int ) const;
            point_function_type point_function_value( &::SireMaths::Torsion::point );
            
            Torsion_exposer.def( 
                "point"
                , point_function_value
                , ( bp::arg("i") )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::SireMaths::Torsion::stream
        
            typedef void ( ::SireMaths::Torsion::*stream_function_type )( ::Siren::Stream & ) ;
            stream_function_type stream_function_value( &::SireMaths::Torsion::stream );
            
            Torsion_exposer.def( 
                "stream"
                , stream_function_value
                , ( bp::arg("s") ) );
        
        }
        { //::SireMaths::Torsion::toString
        
            typedef ::QString ( ::SireMaths::Torsion::*toString_function_type )(  ) const;
            toString_function_type toString_function_value( &::SireMaths::Torsion::toString );
            
            Torsion_exposer.def( 
                "toString"
                , toString_function_value );
        
        }
        { //::SireMaths::Torsion::triangle1
        
            typedef ::SireMaths::Triangle ( ::SireMaths::Torsion::*triangle1_function_type )(  ) const;
            triangle1_function_type triangle1_function_value( &::SireMaths::Torsion::triangle1 );
            
            Torsion_exposer.def( 
                "triangle1"
                , triangle1_function_value );
        
        }
        { //::SireMaths::Torsion::triangle2
        
            typedef ::SireMaths::Triangle ( ::SireMaths::Torsion::*triangle2_function_type )(  ) const;
            triangle2_function_type triangle2_function_value( &::SireMaths::Torsion::triangle2 );
            
            Torsion_exposer.def( 
                "triangle2"
                , triangle2_function_value );
        
        }
        { //::SireMaths::Torsion::vector03
        
            typedef ::SireMaths::Vector ( ::SireMaths::Torsion::*vector03_function_type )(  ) const;
            vector03_function_type vector03_function_value( &::SireMaths::Torsion::vector03 );
            
            Torsion_exposer.def( 
                "vector03"
                , vector03_function_value );
        
        }
        { //::SireMaths::Torsion::vector12
        
            typedef ::SireMaths::Vector ( ::SireMaths::Torsion::*vector12_function_type )(  ) const;
            vector12_function_type vector12_function_value( &::SireMaths::Torsion::vector12 );
            
            Torsion_exposer.def( 
                "vector12"
                , vector12_function_value );
        
        }
        Torsion_exposer.def( "__copy__", &__copy__);
        Torsion_exposer.def( "__deepcopy__", &__copy__);
        Torsion_exposer.def( "clone", &__copy__);
        Torsion_exposer.def( "__str__", &__str__< ::SireMaths::Torsion > );
        Torsion_exposer.def( "__repr__", &__str__< ::SireMaths::Torsion > );
    }

}
