// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "ForceTable.pypp.hpp"

namespace bp = boost::python;

#include "SireError/errors.h"

#include "SireMol/atomselection.h"

#include "SireMol/errors.h"

#include "SireMol/moleculegroup.h"

#include "SireMol/moleculeview.h"

#include "SireMol/mover.hpp"

#include "SireStream/datastream.h"

#include "SireStream/shareddatastream.h"

#include "forcetable.h"

#include "forcetable.h"

SireFF::ForceTable __copy__(const SireFF::ForceTable &other){ return SireFF::ForceTable(other); }

#include "Qt/qdatastream.hpp"

const char* pvt_get_name(const SireFF::ForceTable&){ return "SireFF::ForceTable";}

void register_ForceTable_class(){

    { //::SireFF::ForceTable
        typedef bp::class_< SireFF::ForceTable > ForceTable_exposer_t;
        ForceTable_exposer_t ForceTable_exposer = ForceTable_exposer_t( "ForceTable" );
        bp::scope ForceTable_scope( ForceTable_exposer );
        ForceTable_exposer.def( bp::init< >() );
        ForceTable_exposer.def( bp::init< SireMol::MoleculeGroup const & >(( bp::arg("molgroup") )) );
        ForceTable_exposer.def( bp::init< SireFF::ForceTable const & >(( bp::arg("other") )) );
        { //::SireFF::ForceTable::assertContainsTableFor
        
            typedef void ( ::SireFF::ForceTable::*assertContainsTableFor_function_type )( ::SireMol::MolNum ) const;
            assertContainsTableFor_function_type assertContainsTableFor_function_value( &::SireFF::ForceTable::assertContainsTableFor );
            
            ForceTable_exposer.def( 
                "assertContainsTableFor"
                , assertContainsTableFor_function_value
                , ( bp::arg("molnum") ) );
        
        }
        { //::SireFF::ForceTable::constGetTable
        
            typedef ::SireFF::MolForceTable const & ( ::SireFF::ForceTable::*constGetTable_function_type )( ::SireMol::MolNum ) const;
            constGetTable_function_type constGetTable_function_value( &::SireFF::ForceTable::constGetTable );
            
            ForceTable_exposer.def( 
                "constGetTable"
                , constGetTable_function_value
                , ( bp::arg("molnum") )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::SireFF::ForceTable::containsTable
        
            typedef bool ( ::SireFF::ForceTable::*containsTable_function_type )( ::SireMol::MolNum ) const;
            containsTable_function_type containsTable_function_value( &::SireFF::ForceTable::containsTable );
            
            ForceTable_exposer.def( 
                "containsTable"
                , containsTable_function_value
                , ( bp::arg("molnum") ) );
        
        }
        { //::SireFF::ForceTable::count
        
            typedef int ( ::SireFF::ForceTable::*count_function_type )(  ) const;
            count_function_type count_function_value( &::SireFF::ForceTable::count );
            
            ForceTable_exposer.def( 
                "count"
                , count_function_value );
        
        }
        { //::SireFF::ForceTable::getTable
        
            typedef ::SireFF::MolForceTable const & ( ::SireFF::ForceTable::*getTable_function_type )( ::SireMol::MolNum ) const;
            getTable_function_type getTable_function_value( &::SireFF::ForceTable::getTable );
            
            ForceTable_exposer.def( 
                "getTable"
                , getTable_function_value
                , ( bp::arg("molnum") )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::SireFF::ForceTable::index
        
            typedef ::QHash< SireMol::MolNum, unsigned int > const & ( ::SireFF::ForceTable::*index_function_type )(  ) const;
            index_function_type index_function_value( &::SireFF::ForceTable::index );
            
            ForceTable_exposer.def( 
                "index"
                , index_function_value
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::SireFF::ForceTable::indexOf
        
            typedef int ( ::SireFF::ForceTable::*indexOf_function_type )( ::SireMol::MolNum ) const;
            indexOf_function_type indexOf_function_value( &::SireFF::ForceTable::indexOf );
            
            ForceTable_exposer.def( 
                "indexOf"
                , indexOf_function_value
                , ( bp::arg("molnum") ) );
        
        }
        { //::SireFF::ForceTable::initialiseTable
        
            typedef void ( ::SireFF::ForceTable::*initialiseTable_function_type )( ::SireMol::MolNum ) ;
            initialiseTable_function_type initialiseTable_function_value( &::SireFF::ForceTable::initialiseTable );
            
            ForceTable_exposer.def( 
                "initialiseTable"
                , initialiseTable_function_value
                , ( bp::arg("molnum") ) );
        
        }
        { //::SireFF::ForceTable::initialiseTables
        
            typedef void ( ::SireFF::ForceTable::*initialiseTables_function_type )(  ) ;
            initialiseTables_function_type initialiseTables_function_value( &::SireFF::ForceTable::initialiseTables );
            
            ForceTable_exposer.def( 
                "initialiseTables"
                , initialiseTables_function_value );
        
        }
        { //::SireFF::ForceTable::molNums
        
            typedef ::QList< SireMol::MolNum > ( ::SireFF::ForceTable::*molNums_function_type )(  ) const;
            molNums_function_type molNums_function_value( &::SireFF::ForceTable::molNums );
            
            ForceTable_exposer.def( 
                "molNums"
                , molNums_function_value );
        
        }
        ForceTable_exposer.def( bp::self != bp::self );
        { //::SireFF::ForceTable::operator=
        
            typedef ::SireFF::ForceTable & ( ::SireFF::ForceTable::*assign_function_type )( ::SireFF::ForceTable const & ) ;
            assign_function_type assign_function_value( &::SireFF::ForceTable::operator= );
            
            ForceTable_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        ForceTable_exposer.def( bp::self == bp::self );
        { //::SireFF::ForceTable::typeName
        
            typedef char const * ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::SireFF::ForceTable::typeName );
            
            ForceTable_exposer.def( 
                "typeName"
                , typeName_function_value );
        
        }
        { //::SireFF::ForceTable::what
        
            typedef char const * ( ::SireFF::ForceTable::*what_function_type )(  ) const;
            what_function_type what_function_value( &::SireFF::ForceTable::what );
            
            ForceTable_exposer.def( 
                "what"
                , what_function_value );
        
        }
        ForceTable_exposer.staticmethod( "typeName" );
        ForceTable_exposer.def( "__copy__", &__copy__);
        ForceTable_exposer.def( "__deepcopy__", &__copy__);
        ForceTable_exposer.def( "clone", &__copy__);
        ForceTable_exposer.def( "__rlshift__", &__rlshift__QDataStream< ::SireFF::ForceTable >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        ForceTable_exposer.def( "__rrshift__", &__rrshift__QDataStream< ::SireFF::ForceTable >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        ForceTable_exposer.def( "__str__", &pvt_get_name);
        ForceTable_exposer.def( "__repr__", &pvt_get_name);
    }

}
