// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef FuncDB_hpp__pyplusplus_wrapper
#define FuncDB_hpp__pyplusplus_wrapper

void register_FuncDB_class();

#endif//FuncDB_hpp__pyplusplus_wrapper
