// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "MatchMR.pypp.hpp"
#include "boost/python.hpp"
#include "siredb_headers.h"
#include "SireCAS/function.h"
#include "SireCAS/expression.h"

namespace bp = boost::python;

#include "SirePy/str.hpp"

void register_MatchMR_class(){

    bp::class_< SireDB::MatchMR >( "MatchMR" )    
        .def( bp::init< >() )    
        .def( bp::init< SireDB::MatchMol const & >(( bp::arg("matchmol") )) )    
        .def( bp::init< SireDB::MatchRes const & >(( bp::arg("matchres") )) )    
        .def( bp::init< SireDB::MatchMol const &, SireDB::MatchRes const & >(( bp::arg("matchmol"), bp::arg("matchres") )) )    
        .def( 
            "hasMoleculeCriteria"
            , (bool ( ::SireDB::MatchMR::* )(  ) const)( &::SireDB::MatchMR::hasMoleculeCriteria ) )    
        .def( 
            "hasResidueCriteria"
            , (bool ( ::SireDB::MatchMR::* )(  ) const)( &::SireDB::MatchMR::hasResidueCriteria ) )    
        .def( 
            "isEmpty"
            , (bool ( ::SireDB::MatchMR::* )(  ) const)( &::SireDB::MatchMR::isEmpty ) )    
        .def( 
            "molecule"
            , (::SireDB::MatchMol const & ( ::SireDB::MatchMR::* )(  ) const)( &::SireDB::MatchMR::molecule )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "residue"
            , (::SireDB::MatchRes const & ( ::SireDB::MatchMR::* )(  ) const)( &::SireDB::MatchMR::residue )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "toString"
            , (::QString ( ::SireDB::MatchMR::* )(  ) const)( &::SireDB::MatchMR::toString ) )    
        .def( "__str__", &SirePy::__str__< ::SireDB::MatchMR > );

}
