// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef match_atom_name_hpp__pyplusplus_wrapper
#define match_atom_name_hpp__pyplusplus_wrapper

void register_match_atom_name_class();

#endif//match_atom_name_hpp__pyplusplus_wrapper
