// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "FFCalculatorBase.pypp.hpp"
#include "boost/python.hpp"
#include "sireff_headers.h"
#include "SireMol/molecule.h"
#include "SireMol/residue.h"
#include "SireMol/newatom.h"
#include "SireMol/atom.h"
#include "SireMol/cgatomid.h"
#include "SireMol/cutgroupnum.h"
#include "SireMol/resnumatomid.h"
#include "SireMol/resid.h"
#include "SireMol/moleculeid.h"

namespace bp = boost::python;

const char* pvt_get_name(const SireFF::FFCalculatorBase&){ return "SireFF::FFCalculatorBase";}

void register_FFCalculatorBase_class(){

    bp::class_< SireFF::FFCalculatorBase, boost::noncopyable >( "FFCalculatorBase", bp::no_init )    
        .def( 
            "add"
            , (bool ( ::SireFF::FFCalculatorBase::* )( ::SireMol::Molecule const &,::SireFF::ParameterMap const & ) )( &::SireFF::FFCalculatorBase::add )
            , ( bp::arg("molecule"), bp::arg("map")=::SireFF::ParameterMap( ) ) )    
        .def( 
            "add"
            , (bool ( ::SireFF::FFCalculatorBase::* )( ::SireMol::Residue const &,::SireFF::ParameterMap const & ) )( &::SireFF::FFCalculatorBase::add )
            , ( bp::arg("residue"), bp::arg("map")=::SireFF::ParameterMap( ) ) )    
        .def( 
            "calculateEnergy"
            , (void ( ::SireFF::FFCalculatorBase::* )(  ) )( &::SireFF::FFCalculatorBase::calculateEnergy ) )    
        .def( 
            "change"
            , (bool ( ::SireFF::FFCalculatorBase::* )( ::SireMol::Molecule const & ) )( &::SireFF::FFCalculatorBase::change )
            , ( bp::arg("molecule") ) )    
        .def( 
            "change"
            , (bool ( ::SireFF::FFCalculatorBase::* )( ::SireMol::Residue const & ) )( &::SireFF::FFCalculatorBase::change )
            , ( bp::arg("residue") ) )    
        .def( 
            "forcefield"
            , (::SireFF::ForceField ( ::SireFF::FFCalculatorBase::* )(  ) const)( &::SireFF::FFCalculatorBase::forcefield ) )    
        .def( 
            "getEnergies"
            , (double ( ::SireFF::FFCalculatorBase::* )( ::SireCAS::Values & ) )( &::SireFF::FFCalculatorBase::getEnergies )
            , ( bp::arg("values") ) )    
        .def( 
            "remove"
            , (bool ( ::SireFF::FFCalculatorBase::* )( ::SireMol::Molecule const & ) )( &::SireFF::FFCalculatorBase::remove )
            , ( bp::arg("molecule") ) )    
        .def( 
            "remove"
            , (bool ( ::SireFF::FFCalculatorBase::* )( ::SireMol::Residue const & ) )( &::SireFF::FFCalculatorBase::remove )
            , ( bp::arg("residue") ) )    
        .def( 
            "replace"
            , (bool ( ::SireFF::FFCalculatorBase::* )( ::SireMol::Molecule const &,::SireMol::Molecule const &,::SireFF::ParameterMap const & ) )( &::SireFF::FFCalculatorBase::replace )
            , ( bp::arg("oldmol"), bp::arg("newmol"), bp::arg("map")=::SireFF::ParameterMap( ) ) )    
        .def( 
            "setForceField"
            , (bool ( ::SireFF::FFCalculatorBase::* )( ::SireFF::ForceField const & ) )( &::SireFF::FFCalculatorBase::setForceField )
            , ( bp::arg("forcefield") ) )    
        .def( "__str__", &pvt_get_name);

}
