// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "ForceField.pypp.hpp"
#include "boost/python.hpp"
#include "sireff_headers.h"
#include "SireMol/molecule.h"
#include "SireMol/residue.h"
#include "SireMol/newatom.h"
#include "SireMol/atom.h"
#include "SireMol/cgatomid.h"
#include "SireMol/cutgroupnum.h"
#include "SireMol/resnumatomid.h"
#include "SireMol/resid.h"
#include "SireMol/moleculeid.h"

namespace bp = boost::python;

void register_ForceField_class(){

    bp::class_< SireFF::ForceField >( "ForceField" )    
        .def( bp::init< >() )    
        .def( bp::init< SireFF::FFBase const & >(( bp::arg("ffbase") )) )    
        .def( bp::init< SireBase::SharedPolyPointer<SireFF::FFBase> const & >(( bp::arg("ffptr") )) )    
        .def( 
            "ID"
            , (::SireFF::ForceFieldID ( ::SireFF::ForceField::* )(  ) const)( &::SireFF::ForceField::ID ) )    
        .def( 
            "add"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::Molecule const &,::SireFF::ParameterMap const & ) )( &::SireFF::ForceField::add )
            , ( bp::arg("molecule"), bp::arg("map")=::SireFF::ParameterMap( ) ) )    
        .def( 
            "add"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::Residue const &,::SireFF::ParameterMap const & ) )( &::SireFF::ForceField::add )
            , ( bp::arg("residue"), bp::arg("map")=::SireFF::ParameterMap( ) ) )    
        .def( 
            "add"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::NewAtom const &,::SireFF::ParameterMap const & ) )( &::SireFF::ForceField::add )
            , ( bp::arg("atom"), bp::arg("map")=::SireFF::ParameterMap( ) ) )    
        .def( 
            "assertContains"
            , (void ( ::SireFF::ForceField::* )( ::SireFF::FFComponent const & ) const)( &::SireFF::ForceField::assertContains )
            , ( bp::arg("component") ) )    
        .def( 
            "atom"
            , (::SireMol::NewAtom ( ::SireFF::ForceField::* )( ::SireMol::MoleculeID,::SireMol::IDMolAtom const & ) const)( &::SireFF::ForceField::atom )
            , ( bp::arg("molid"), bp::arg("atomid") ) )    
        .def( 
            "atom"
            , (::SireMol::NewAtom ( ::SireFF::ForceField::* )( ::SireMol::NewAtom const & ) const)( &::SireFF::ForceField::atom )
            , ( bp::arg("atom") ) )    
        .def( 
            "change"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::Molecule const & ) )( &::SireFF::ForceField::change )
            , ( bp::arg("mol") ) )    
        .def( 
            "change"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::Residue const & ) )( &::SireFF::ForceField::change )
            , ( bp::arg("res") ) )    
        .def( 
            "change"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::NewAtom const & ) )( &::SireFF::ForceField::change )
            , ( bp::arg("atom") ) )    
        .def( 
            "change"
            , (bool ( ::SireFF::ForceField::* )( ::QHash<SireMol::MoleculeID, SireMol::Molecule> const & ) )( &::SireFF::ForceField::change )
            , ( bp::arg("molecules") ) )    
        .def( 
            "components"
            , (::SireFF::FFBase::Components const & ( ::SireFF::ForceField::* )(  ) const)( &::SireFF::ForceField::components )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "contains"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::Molecule const & ) const)( &::SireFF::ForceField::contains )
            , ( bp::arg("molecule") ) )    
        .def( 
            "contains"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::Residue const & ) const)( &::SireFF::ForceField::contains )
            , ( bp::arg("residue") ) )    
        .def( 
            "contains"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::NewAtom const & ) const)( &::SireFF::ForceField::contains )
            , ( bp::arg("atom") ) )    
        .def( 
            "energies"
            , (::SireCAS::Values ( ::SireFF::ForceField::* )(  ) )( &::SireFF::ForceField::energies ) )    
        .def( 
            "energies"
            , (::SireCAS::Values ( ::SireFF::ForceField::* )( ::QSet<SireFF::FFComponent> const & ) )( &::SireFF::ForceField::energies )
            , ( bp::arg("components") ) )    
        .def( 
            "energy"
            , (double ( ::SireFF::ForceField::* )(  ) )( &::SireFF::ForceField::energy ) )    
        .def( 
            "energy"
            , (double ( ::SireFF::ForceField::* )( ::SireFF::FFComponent const & ) )( &::SireFF::ForceField::energy )
            , ( bp::arg("component") ) )    
        .def( 
            "isClean"
            , (bool ( ::SireFF::ForceField::* )(  ) const)( &::SireFF::ForceField::isClean ) )    
        .def( 
            "isDirty"
            , (bool ( ::SireFF::ForceField::* )(  ) const)( &::SireFF::ForceField::isDirty ) )    
        .def( 
            "molecule"
            , (::SireMol::Molecule ( ::SireFF::ForceField::* )( ::SireMol::MoleculeID ) const)( &::SireFF::ForceField::molecule )
            , ( bp::arg("molid") ) )    
        .def( 
            "molecule"
            , (::SireMol::Molecule ( ::SireFF::ForceField::* )( ::SireMol::Molecule const & ) const)( &::SireFF::ForceField::molecule )
            , ( bp::arg("mol") ) )    
        .def( 
            "moleculeIDs"
            , (::QSet<SireMol::MoleculeID> ( ::SireFF::ForceField::* )(  ) const)( &::SireFF::ForceField::moleculeIDs ) )    
        .def( 
            "name"
            , (::QString const & ( ::SireFF::ForceField::* )(  ) const)( &::SireFF::ForceField::name )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "parameters"
            , (::SireFF::FFBase::Parameters const & ( ::SireFF::ForceField::* )(  ) const)( &::SireFF::ForceField::parameters )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "refersTo"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::Molecule const & ) const)( &::SireFF::ForceField::refersTo )
            , ( bp::arg("molecule") ) )    
        .def( 
            "remove"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::Molecule const & ) )( &::SireFF::ForceField::remove )
            , ( bp::arg("molecule") ) )    
        .def( 
            "remove"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::Residue const & ) )( &::SireFF::ForceField::remove )
            , ( bp::arg("residue") ) )    
        .def( 
            "remove"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::NewAtom const & ) )( &::SireFF::ForceField::remove )
            , ( bp::arg("atom") ) )    
        .def( 
            "replace"
            , (bool ( ::SireFF::ForceField::* )( ::SireMol::Molecule const &,::SireMol::Molecule const &,::SireFF::ParameterMap const & ) )( &::SireFF::ForceField::replace )
            , ( bp::arg("oldmol"), bp::arg("newmol"), bp::arg("map")=::SireFF::ParameterMap( ) ) )    
        .def( 
            "residue"
            , (::SireMol::Residue ( ::SireFF::ForceField::* )( ::SireMol::MoleculeID,::SireMol::ResNum ) const)( &::SireFF::ForceField::residue )
            , ( bp::arg("molid"), bp::arg("resnum") ) )    
        .def( 
            "residue"
            , (::SireMol::Residue ( ::SireFF::ForceField::* )( ::SireMol::Residue const & ) const)( &::SireFF::ForceField::residue )
            , ( bp::arg("res") ) )    
        .def( 
            "setName"
            , (void ( ::SireFF::ForceField::* )( ::QString const & ) )( &::SireFF::ForceField::setName )
            , ( bp::arg("name") ) )    
        .def( 
            "version"
            , (::SireBase::Version const & ( ::SireFF::ForceField::* )(  ) const)( &::SireFF::ForceField::version )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "what"
            , (char const * ( ::SireFF::ForceField::* )(  ) const)( &::SireFF::ForceField::what ) );

}
