// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef MoleculeBonds_hpp__pyplusplus_wrapper
#define MoleculeBonds_hpp__pyplusplus_wrapper

void register_MoleculeBonds_class();

#endif//MoleculeBonds_hpp__pyplusplus_wrapper
