// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License


#include "boost/python.hpp"

#include "sirecas_headers.h"

#include "ArcCos.pypp.hpp"

#include "ArcCosh.pypp.hpp"

#include "ArcCot.pypp.hpp"

#include "ArcCoth.pypp.hpp"

#include "ArcCsc.pypp.hpp"

#include "ArcCsch.pypp.hpp"

#include "ArcSec.pypp.hpp"

#include "ArcSech.pypp.hpp"

#include "ArcSin.pypp.hpp"

#include "ArcSinh.pypp.hpp"

#include "ArcTan.pypp.hpp"

#include "ArcTanh.pypp.hpp"

#include "ComplexPower.pypp.hpp"

#include "ComplexValues.pypp.hpp"

#include "Constant.pypp.hpp"

#include "ConstantPower.pypp.hpp"

#include "Cos.pypp.hpp"

#include "Cosh.pypp.hpp"

#include "Cot.pypp.hpp"

#include "Coth.pypp.hpp"

#include "Csc.pypp.hpp"

#include "Csch.pypp.hpp"

#include "ExBase.pypp.hpp"

#include "Exp.pypp.hpp"

#include "Expression.pypp.hpp"

#include "ExpressionBase.pypp.hpp"

#include "Function.pypp.hpp"

#include "I.pypp.hpp"

#include "Identities.pypp.hpp"

#include "IntegerPower.pypp.hpp"

#include "IntegrationConstant.pypp.hpp"

#include "Ln.pypp.hpp"

#include "Power.pypp.hpp"

#include "PowerConstant.pypp.hpp"

#include "PowerFunction.pypp.hpp"

#include "Product.pypp.hpp"

#include "RationalPower.pypp.hpp"

#include "RealPower.pypp.hpp"

#include "Sec.pypp.hpp"

#include "Sech.pypp.hpp"

#include "Sin.pypp.hpp"

#include "SingleFunc.pypp.hpp"

#include "Sinh.pypp.hpp"

#include "Sum.pypp.hpp"

#include "Symbol.pypp.hpp"

#include "SymbolComplex.pypp.hpp"

#include "SymbolExpression.pypp.hpp"

#include "SymbolValue.pypp.hpp"

#include "Tan.pypp.hpp"

#include "Tanh.pypp.hpp"

#include "Values.pypp.hpp"

#include "sirecas_containers.h"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_CAS){
    register_SireCAS_containers();

    register_ExBase_class();

    register_SingleFunc_class();

    register_ArcCos_class();

    register_ArcCosh_class();

    register_ArcCot_class();

    register_ArcCoth_class();

    register_ArcCsc_class();

    register_ArcCsch_class();

    register_ArcSec_class();

    register_ArcSech_class();

    register_ArcSin_class();

    register_ArcSinh_class();

    register_ArcTan_class();

    register_ArcTanh_class();

    register_PowerFunction_class();

    register_ConstantPower_class();

    register_ComplexPower_class();

    register_ComplexValues_class();

    register_Constant_class();

    register_Cos_class();

    register_Cosh_class();

    register_Cot_class();

    register_Coth_class();

    register_Csc_class();

    register_Csch_class();

    register_Exp_class();

    register_Expression_class();

    register_ExpressionBase_class();

    register_Symbol_class();

    register_Function_class();

    register_I_class();

    register_Identities_class();

    register_IntegerPower_class();

    register_IntegrationConstant_class();

    register_Ln_class();

    register_Power_class();

    register_PowerConstant_class();

    register_Product_class();

    register_RationalPower_class();

    register_RealPower_class();

    register_Sec_class();

    register_Sech_class();

    register_Sin_class();

    register_Sinh_class();

    register_Sum_class();

    register_SymbolComplex_class();

    register_SymbolExpression_class();

    register_SymbolValue_class();

    register_Tan_class();

    register_Tanh_class();

    bp::implicitly_convertible< SireCAS::SymbolComplex, SireCAS::ComplexValues >();

    bp::implicitly_convertible< QList<SireCAS::SymbolComplex>, SireCAS::ComplexValues >();

    bp::implicitly_convertible< QHash<SireCAS::Symbol,SireMaths::Complex>, SireCAS::ComplexValues >();

    bp::implicitly_convertible< const SireCAS::ExBase&, SireCAS::Expression >();

    bp::implicitly_convertible< QList<SireCAS::SymbolExpression>, SireCAS::Identities >();

    bp::implicitly_convertible< QHash<SireCAS::Symbol,SireCAS::Expression>, SireCAS::Identities >();

    bp::implicitly_convertible< SireCAS::SymbolExpression, SireCAS::Identities >();

    bp::implicitly_convertible< QList<SireCAS::SymbolValue>, SireCAS::Values >();

    bp::implicitly_convertible< QHash<SireCAS::Symbol,double>, SireCAS::Values >();

    bp::implicitly_convertible< SireCAS::SymbolValue, SireCAS::Values >();

    register_Values_class();
}

