// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "Coth.pypp.hpp"
#include "boost/python.hpp"
#include "sirecas_headers.h"

namespace bp = boost::python;

#include "SireQt/qdatastream.hpp"

#include "SirePy/str.hpp"

void register_Coth_class(){

    bp::class_< SireCAS::Coth, bp::bases< SireCAS::SingleFunc > >( "Coth" )    
        .def( bp::init< >() )    
        .def( bp::init< SireCAS::Expression const & >(( bp::arg("ex") )) )    
        .def( 
            "evaluate"
            , (double ( ::SireCAS::Coth::* )( ::SireCAS::Values const & ) const)( &::SireCAS::Coth::evaluate )
            , ( bp::arg("values") ) )    
        .def( 
            "evaluate"
            , (::SireMaths::Complex ( ::SireCAS::Coth::* )( ::SireCAS::ComplexValues const & ) const)( &::SireCAS::Coth::evaluate )
            , ( bp::arg("values") ) )    
        .def( bp::self == bp::other< SireCAS::ExBase >() )    
        .def( 
            "typeName"
            , (char const * (*)(  ))( &::SireCAS::Coth::typeName ) )    
        .def( 
            "what"
            , (char const * ( ::SireCAS::Coth::* )(  ) const)( &::SireCAS::Coth::what ) )    
        .staticmethod( "typeName" )    
        .def( "__rlshift__", &SireQt::__rlshift__QDataStream< ::SireCAS::Coth >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() )    
        .def( "__rrshift__", &SireQt::__rrshift__QDataStream< ::SireCAS::Coth >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() )    
        .def( "__str__", &SirePy::__str__< ::SireCAS::Coth > );

}
