// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "RationalPower.pypp.hpp"
#include "boost/python.hpp"
#include "sirecas_headers.h"

namespace bp = boost::python;

void register_RationalPower_class(){

    bp::class_< SireCAS::RationalPower, bp::bases< SireCAS::ConstantPower > >( "RationalPower" )    
        .def( bp::init< >() )    
        .def( bp::init< SireCAS::Expression const &, SireMaths::Rational const & >(( bp::arg("expression"), bp::arg("power") )) )    
        .def( 
            "evaluate"
            , (double ( ::SireCAS::RationalPower::* )( ::SireCAS::Values const & ) const)( &::SireCAS::RationalPower::evaluate )
            , ( bp::arg("values") ) )    
        .def( 
            "evaluate"
            , (::SireMaths::Complex ( ::SireCAS::RationalPower::* )( ::SireCAS::ComplexValues const & ) const)( &::SireCAS::RationalPower::evaluate )
            , ( bp::arg("values") ) )    
        .def( 
            "hash"
            , (::uint ( ::SireCAS::RationalPower::* )(  ) const)( &::SireCAS::RationalPower::hash ) )    
        .def( bp::self == bp::other< SireCAS::ExBase >() )    
        .def( 
            "power"
            , (::SireCAS::Expression ( ::SireCAS::RationalPower::* )(  ) const)( &::SireCAS::RationalPower::power ) )    
        .def( 
            "typeName"
            , (char const * (*)(  ))( &::SireCAS::RationalPower::typeName ) )    
        .def( 
            "what"
            , (char const * ( ::SireCAS::RationalPower::* )(  ) const)( &::SireCAS::RationalPower::what ) )    
        .staticmethod( "typeName" );

}
