// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "RealPower.pypp.hpp"
#include "boost/python.hpp"
#include "sirecas_headers.h"

namespace bp = boost::python;

#include "SireQt/qdatastream.hpp"

#include "SirePy/str.hpp"

void register_RealPower_class(){

    bp::class_< SireCAS::RealPower, bp::bases< SireCAS::ConstantPower > >( "RealPower" )    
        .def( bp::init< >() )    
        .def( bp::init< SireCAS::Expression const &, double >(( bp::arg("expression"), bp::arg("power") )) )    
        .def( 
            "evaluate"
            , (double ( ::SireCAS::RealPower::* )( ::SireCAS::Values const & ) const)( &::SireCAS::RealPower::evaluate )
            , ( bp::arg("values") ) )    
        .def( 
            "evaluate"
            , (::SireMaths::Complex ( ::SireCAS::RealPower::* )( ::SireCAS::ComplexValues const & ) const)( &::SireCAS::RealPower::evaluate )
            , ( bp::arg("values") ) )    
        .def( 
            "hash"
            , (::uint ( ::SireCAS::RealPower::* )(  ) const)( &::SireCAS::RealPower::hash ) )    
        .def( bp::self == bp::other< SireCAS::ExBase >() )    
        .def( 
            "power"
            , (::SireCAS::Expression ( ::SireCAS::RealPower::* )(  ) const)( &::SireCAS::RealPower::power ) )    
        .def( 
            "typeName"
            , (char const * (*)(  ))( &::SireCAS::RealPower::typeName ) )    
        .def( 
            "what"
            , (char const * ( ::SireCAS::RealPower::* )(  ) const)( &::SireCAS::RealPower::what ) )    
        .staticmethod( "typeName" )    
        .def( "__rlshift__", &SireQt::__rlshift__QDataStream< ::SireCAS::RealPower >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() )    
        .def( "__rrshift__", &SireQt::__rrshift__QDataStream< ::SireCAS::RealPower >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() )    
        .def( "__str__", &SirePy::__str__< ::SireCAS::RealPower > );

}
