// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "Sinh.pypp.hpp"
#include "boost/python.hpp"
#include "sirecas_headers.h"

namespace bp = boost::python;

void register_Sinh_class(){

    bp::class_< SireCAS::Sinh, bp::bases< SireCAS::SingleFunc > >( "Sinh" )    
        .def( bp::init< >() )    
        .def( bp::init< SireCAS::Expression const & >(( bp::arg("ex") )) )    
        .def( 
            "evaluate"
            , (double ( ::SireCAS::Sinh::* )( ::SireCAS::Values const & ) const)( &::SireCAS::Sinh::evaluate )
            , ( bp::arg("values") ) )    
        .def( 
            "evaluate"
            , (::SireMaths::Complex ( ::SireCAS::Sinh::* )( ::SireCAS::ComplexValues const & ) const)( &::SireCAS::Sinh::evaluate )
            , ( bp::arg("values") ) )    
        .def( bp::self == bp::other< SireCAS::ExBase >() )    
        .def( 
            "typeName"
            , (char const * (*)(  ))( &::SireCAS::Sinh::typeName ) )    
        .def( 
            "what"
            , (char const * ( ::SireCAS::Sinh::* )(  ) const)( &::SireCAS::Sinh::what ) )    
        .staticmethod( "typeName" );

}
