// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef IDMolAtom_hpp__pyplusplus_wrapper
#define IDMolAtom_hpp__pyplusplus_wrapper

void register_IDMolAtom_class();

#endif//IDMolAtom_hpp__pyplusplus_wrapper
