// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef MoleculeID_hpp__pyplusplus_wrapper
#define MoleculeID_hpp__pyplusplus_wrapper

void register_MoleculeID_class();

#endif//MoleculeID_hpp__pyplusplus_wrapper
