// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef MutexLocker_hpp__pyplusplus_wrapper
#define MutexLocker_hpp__pyplusplus_wrapper

void register_MutexLocker_class();

#endif//MutexLocker_hpp__pyplusplus_wrapper
