// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef AngleGenerator_hpp__pyplusplus_wrapper
#define AngleGenerator_hpp__pyplusplus_wrapper

void register_AngleGenerator_class();

#endif//AngleGenerator_hpp__pyplusplus_wrapper
