// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef AtomicLJs_hpp__pyplusplus_wrapper
#define AtomicLJs_hpp__pyplusplus_wrapper

void register_AtomicLJs_class();

#endif//AtomicLJs_hpp__pyplusplus_wrapper
