// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "Celsius.pypp.hpp"

namespace bp = boost::python;

#include "temperature.h"

#include <QDebug>

#include "temperature.h"

#include "Siren/logger.h"

SireUnits::Celsius __copy__(const SireUnits::Celsius &other){ return SireUnits::Celsius(other); }

#include "Siren/str.hpp"

void register_Celsius_class(){

    { //::SireUnits::Celsius
        typedef bp::class_< SireUnits::Celsius, bp::bases< SireUnits::Dimension::detail::Temperature, Siren::Object > > Celsius_exposer_t;
        Celsius_exposer_t Celsius_exposer = Celsius_exposer_t( "Celsius" );
        bp::scope Celsius_scope( Celsius_exposer );
        Celsius_exposer.def( bp::init< >() );
        Celsius_exposer.def( bp::init< double >(( bp::arg("value") )) );
        Celsius_exposer.def( bp::init< SireUnits::Dimension::Temperature const & >(( bp::arg("temperature") )) );
        Celsius_exposer.def( bp::init< SireUnits::Dimension::detail::Temperature const & >(( bp::arg("temperature") )) );
        Celsius_exposer.def( bp::init< SireUnits::Celsius const & >(( bp::arg("other") )) );
        { //::SireUnits::Celsius::convertFromInternal
        
            typedef double ( ::SireUnits::Celsius::*convertFromInternal_function_type )( double ) const;
            convertFromInternal_function_type convertFromInternal_function_value( &::SireUnits::Celsius::convertFromInternal );
            
            Celsius_exposer.def( 
                "convertFromInternal"
                , convertFromInternal_function_value
                , ( bp::arg("value") ) );
        
        }
        { //::SireUnits::Celsius::convertFromInternal
        
            typedef double ( ::SireUnits::Celsius::*convertFromInternal_function_type )(  ) const;
            convertFromInternal_function_type convertFromInternal_function_value( &::SireUnits::Celsius::convertFromInternal );
            
            Celsius_exposer.def( 
                "convertFromInternal"
                , convertFromInternal_function_value );
        
        }
        { //::SireUnits::Celsius::convertToInternal
        
            typedef double ( ::SireUnits::Celsius::*convertToInternal_function_type )( double ) const;
            convertToInternal_function_type convertToInternal_function_value( &::SireUnits::Celsius::convertToInternal );
            
            Celsius_exposer.def( 
                "convertToInternal"
                , convertToInternal_function_value
                , ( bp::arg("value") ) );
        
        }
        Celsius_exposer.def( bp::self != bp::self );
        Celsius_exposer.def( bp::self * bp::other< double >() );
        Celsius_exposer.def( bp::self * bp::other< int >() );
        Celsius_exposer.def( bp::self + bp::self );
        Celsius_exposer.def( -bp::self );
        Celsius_exposer.def( bp::self - bp::self );
        Celsius_exposer.def( bp::self / bp::other< double >() );
        Celsius_exposer.def( bp::self / bp::other< int >() );
        { //::SireUnits::Celsius::operator=
        
            typedef ::SireUnits::Celsius & ( ::SireUnits::Celsius::*assign_function_type )( ::SireUnits::Celsius const & ) ;
            assign_function_type assign_function_value( &::SireUnits::Celsius::operator= );
            
            Celsius_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >() );
        
        }
        Celsius_exposer.def( bp::self == bp::self );
        { //::SireUnits::Celsius::stream
        
            typedef void ( ::SireUnits::Celsius::*stream_function_type )( ::Siren::Stream & ) ;
            stream_function_type stream_function_value( &::SireUnits::Celsius::stream );
            
            Celsius_exposer.def( 
                "stream"
                , stream_function_value
                , ( bp::arg("s") ) );
        
        }
        { //::SireUnits::Celsius::toString
        
            typedef ::QString ( ::SireUnits::Celsius::*toString_function_type )(  ) const;
            toString_function_type toString_function_value( &::SireUnits::Celsius::toString );
            
            Celsius_exposer.def( 
                "toString"
                , toString_function_value );
        
        }
        Celsius_exposer.def( bp::other< int >() * bp::self );
        Celsius_exposer.def( bp::other< double >() * bp::self );
        Celsius_exposer.def( bp::other< int >() / bp::self );
        Celsius_exposer.def( bp::other< double >() / bp::self );
        Celsius_exposer.def( bp::other<double>() * bp::self );
        Celsius_exposer.def( bp::other<double>() / bp::self );
        Celsius_exposer.def( "__copy__", &__copy__);
        Celsius_exposer.def( "__deepcopy__", &__copy__);
        Celsius_exposer.def( "clone", &__copy__);
        Celsius_exposer.def( "__str__", &__str__< ::SireUnits::Celsius > );
        Celsius_exposer.def( "__repr__", &__str__< ::SireUnits::Celsius > );
    }

}
