// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef ConcreteProperty_PeriodicBox_Cartesian__hpp__pyplusplus_wrapper
#define ConcreteProperty_PeriodicBox_Cartesian__hpp__pyplusplus_wrapper

void register_ConcreteProperty_PeriodicBox_Cartesian__class();

#endif//ConcreteProperty_PeriodicBox_Cartesian__hpp__pyplusplus_wrapper
