// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#include "ConcreteProperty_PeriodicBox_Cartesian_.pypp.hpp"
#include "boost/python.hpp"
#include "sirevol_headers.h"
#include "SireMaths/vector.h"
#include "SireMaths/quaternion.h"
#include "SireMaths/matrix.h"

namespace bp = boost::python;

SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian> __copy__(const SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian> &other){ return SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>(other); }

const char* pvt_get_name(const SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>&){ return "SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>";}

void register_ConcreteProperty_PeriodicBox_Cartesian__class(){

    bp::class_< SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>, bp::bases< SireVol::SpaceBase, SireBase::PropertyBase > >( "ConcreteProperty_PeriodicBox_Cartesian_" )    
        .def( bp::init< >() )    
        .def( 
            "compare"
            , (bool ( ::SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>::* )( ::SireBase::PropertyBase const & ) const)( &::SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>::compare )
            , ( bp::arg("other") ) )    
        .def( 
            "copy"
            , (void ( ::SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>::* )( ::SireBase::PropertyBase const & ) )( &::SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>::copy )
            , ( bp::arg("other") ) )    
        .def( 
            "load"
            , (void ( ::SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>::* )( ::QDataStream & ) )( &::SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>::load )
            , ( bp::arg("ds") ) )    
        .def( bp::self != bp::other< SireBase::PropertyBase >() )    
        .def( bp::self == bp::other< SireBase::PropertyBase >() )    
        .def( 
            "save"
            , (void ( ::SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>::* )( ::QDataStream & ) const)( &::SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>::save )
            , ( bp::arg("ds") ) )    
        .def( 
            "what"
            , (char const * ( ::SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>::* )(  ) const)( &::SireBase::ConcreteProperty<SireVol::PeriodicBox, SireVol::Cartesian>::what ) )    
        .def( "__copy__", &__copy__)    
        .def( "__str__", &pvt_get_name);

}
