// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef ChargeTable_hpp__pyplusplus_wrapper
#define ChargeTable_hpp__pyplusplus_wrapper

void register_ChargeTable_class();

#endif//ChargeTable_hpp__pyplusplus_wrapper
