//WARNING - AUTOGENERATED FILE - CONTENTS WILL BE OVERWRITTEN!
#include "SireDB_registrars.h"

#include "errors.h"

#include "Helpers/objectregistry.hpp"

void register_SireDB_objects()
{

    ObjectRegistry::registerConverterFor< SireDB::database_error >();

}

