// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef assign_internals_MolDihedralInfo__hpp__pyplusplus_wrapper
#define assign_internals_MolDihedralInfo__hpp__pyplusplus_wrapper

void register_assign_internals_MolDihedralInfo__class();

#endif//assign_internals_MolDihedralInfo__hpp__pyplusplus_wrapper
