// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef ChargeDB_hpp__pyplusplus_wrapper
#define ChargeDB_hpp__pyplusplus_wrapper

void register_ChargeDB_class();

#endif//ChargeDB_hpp__pyplusplus_wrapper
