// This file has been generated by Py++.

// (C) Christopher Woods, GPL >=2 License

#ifndef UsePassedAngles_hpp__pyplusplus_wrapper
#define UsePassedAngles_hpp__pyplusplus_wrapper

void register_UsePassedAngles_class();

#endif//UsePassedAngles_hpp__pyplusplus_wrapper
