#ifndef SIREGLOBAL_H
#define SIREGLOBAL_H

#include "Siren/sirenglobal.h"

#define SIRE_BEGIN_HEADER SIREN_BEGIN_HEADER
#define SIRE_END_HEADER SIREN_END_HEADER

#define SIRE_EXPOSE_FUNCTION SIREN_EXPOSE_FUNCTION
#define SIRE_EXPOSE_CLASS SIREN_EXPOSE_CLASS
#define SIRE_EXPOSE_ALIAS SIREN_EXPOSE_ALIAS
#define SIRE_EXPOSE_OBJECT_PTR SIREN_EXPOSE_OBJECT_PTR
#define SIRE_EXPOSE_HANDLE_PTR SIREN_EXPOSE_HANDLE_PTR
#define SIRE_EXPOSE_PRIMITIVE SIREN_EXPOSE_PRIMITIVE

#define SIRE_EXPOSE_ATOM_PROPERTY(c,a) /* Exposing atom property #1 with alias #2 */
#define SIRE_EXPOSE_CUTGROUP_PROPERTY(c,a) /* Exposing CutGroup property #1 with alias #2 */
#define SIRE_EXPOSE_RESIDUE_PROPERTY(c,a) /* Exposing residue property #1 with alias #2 */
#define SIRE_EXPOSE_CHAIN_PROPERTY(c,a) /* Exposing chain property #1 with alias #2 */
#define SIRE_EXPOSE_SEGMENT_PROPERTY(c,a) /* Exposing segment property #1 with alias #2 */

#define SIRE_OUTOFLINE_TEMPLATE SIREN_OUTOFLINE_TEMPLATE
#define SIRE_INLINE_TEMPLATE SIREN_INLINE_TEMPLATE

#define SIRE_EXPORT SIREN_EXPORT
#define SIRE_IMPORT SIREN_IMPORT

#define SIREBASE_EXPORT SIRE_EXPORT
#define SIRECAS_EXPORT SIRE_EXPORT
#define SIRECLUSTER_EXPORT SIRE_EXPORT
#define SIREDB_EXPORT SIRE_EXPORT
#define SIREFF_EXPORT SIRE_EXPORT
#define SIREID_EXPORT SIRE_EXPORT
#define SIREIO_EXPORT SIRE_EXPORT
#define SIREMM_EXPORT SIRE_EXPORT
#define SIREMMDB_EXPORT SIRE_EXPORT
#define SIREMATHS_EXPORT SIRE_EXPORT
#define SIREMOL_EXPORT SIRE_EXPORT
#define SIREMOVE_EXPORT SIRE_EXPORT
#define SIREMPI_EXPORT SIRE_EXPORT
#define SIREPY_EXPORT SIRE_EXPORT
#define SIREQT_EXPORT SIRE_EXPORT
#define SIRESYSTEM_EXPORT SIRE_EXPORT
#define SIRETEST_EXPORT SIRE_EXPORT
#define SIREUNITTEST_EXPORT SIRE_EXPORT
#define SIREUNITS_EXPORT SIRE_EXPORT
#define SIREVOL_EXPORT SIRE_EXPORT
#define SPIER_EXPORT SIRE_EXPORT
#define SQUIRE_EXPORT SIRE_EXPORT

#endif // SIREGLOBAL_H
