// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef DirValue_hpp__pyplusplus_wrapper
#define DirValue_hpp__pyplusplus_wrapper

void register_DirValue_class();

#endif//DirValue_hpp__pyplusplus_wrapper
